// Code generated by ent, DO NOT EDIT.

package importerconfig

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the importerconfig type in the database.
	Label = "importer_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldSyncIntervalSeconds holds the string denoting the sync_interval_seconds field in the database.
	FieldSyncIntervalSeconds = "sync_interval_seconds"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the importerconfig in the database.
	Table = "importer_configs"
)

// Columns holds all SQL columns for importerconfig fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldProvider,
	FieldCredentials,
	FieldSyncIntervalSeconds,
	FieldLastSyncAt,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultSyncIntervalSeconds holds the default value on creation for the "sync_interval_seconds" field.
	DefaultSyncIntervalSeconds int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// Provider defines the type for the "provider" enum field.
type Provider string

// Provider values.
const (
	ProviderManual        Provider = "manual"
	ProviderDNSBruteforce Provider = "dns_bruteforce"
	ProviderHetznerCloud  Provider = "hetzner_cloud"
	ProviderHetznerRobot  Provider = "hetzner_robot"
	ProviderNamecheap     Provider = "namecheap"
	ProviderGandi         Provider = "gandi"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderManual, ProviderDNSBruteforce, ProviderHetznerCloud, ProviderHetznerRobot, ProviderNamecheap, ProviderGandi:
		return nil
	default:
		return fmt.Errorf("importerconfig: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the ImporterConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// BySyncIntervalSeconds orders the results by the sync_interval_seconds field.
func BySyncIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncIntervalSeconds, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
