// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CspScansColumns holds the columns for the "csp_scans" table.
	CspScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "csp_header", Type: field.TypeString},
		{Name: "findings", Type: field.TypeJSON, Nullable: true},
		{Name: "target_csp_scans", Type: field.TypeInt},
	}
	// CspScansTable holds the schema information for the "csp_scans" table.
	CspScansTable = &schema.Table{
		Name:       "csp_scans",
		Columns:    CspScansColumns,
		PrimaryKey: []*schema.Column{CspScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "csp_scans_targets_csp_scans",
				Columns:    []*schema.Column{CspScansColumns[4]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// IpsColumns holds the columns for the "ips" table.
	IpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "address", Type: field.TypeString, Unique: true},
	}
	// IpsTable holds the schema information for the "ips" table.
	IpsTable = &schema.Table{
		Name:       "ips",
		Columns:    IpsColumns,
		PrimaryKey: []*schema.Column{IpsColumns[0]},
	}
	// PortsColumns holds the columns for the "ports" table.
	PortsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeInt},
		{Name: "port_scan_ports", Type: field.TypeInt},
	}
	// PortsTable holds the schema information for the "ports" table.
	PortsTable = &schema.Table{
		Name:       "ports",
		Columns:    PortsColumns,
		PrimaryKey: []*schema.Column{PortsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ports_port_scans_ports",
				Columns:    []*schema.Column{PortsColumns[2]},
				RefColumns: []*schema.Column{PortScansColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PortScansColumns holds the columns for the "port_scans" table.
	PortScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "ip_scans", Type: field.TypeInt},
	}
	// PortScansTable holds the schema information for the "port_scans" table.
	PortScansTable = &schema.Table{
		Name:       "port_scans",
		Columns:    PortScansColumns,
		PrimaryKey: []*schema.Column{PortScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_scans_ips_scans",
				Columns:    []*schema.Column{PortScansColumns[2]},
				RefColumns: []*schema.Column{IpsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SslScansColumns holds the columns for the "ssl_scans" table.
	SslScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "grade", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "cert_issuer", Type: field.TypeString, Nullable: true},
		{Name: "cert_subject", Type: field.TypeString, Nullable: true},
		{Name: "cert_expiry", Type: field.TypeTime, Nullable: true},
		{Name: "protocols", Type: field.TypeJSON, Nullable: true},
		{Name: "vulnerabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "target_ssl_scans", Type: field.TypeInt},
	}
	// SslScansTable holds the schema information for the "ssl_scans" table.
	SslScansTable = &schema.Table{
		Name:       "ssl_scans",
		Columns:    SslScansColumns,
		PrimaryKey: []*schema.Column{SslScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ssl_scans_targets_ssl_scans",
				Columns:    []*schema.Column{SslScansColumns[9]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "input", Type: field.TypeString, Unique: true},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
	}
	// TargetIpsColumns holds the columns for the "target_ips" table.
	TargetIpsColumns = []*schema.Column{
		{Name: "target_id", Type: field.TypeInt},
		{Name: "ip_id", Type: field.TypeInt},
	}
	// TargetIpsTable holds the schema information for the "target_ips" table.
	TargetIpsTable = &schema.Table{
		Name:       "target_ips",
		Columns:    TargetIpsColumns,
		PrimaryKey: []*schema.Column{TargetIpsColumns[0], TargetIpsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "target_ips_target_id",
				Columns:    []*schema.Column{TargetIpsColumns[0]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "target_ips_ip_id",
				Columns:    []*schema.Column{TargetIpsColumns[1]},
				RefColumns: []*schema.Column{IpsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CspScansTable,
		IpsTable,
		PortsTable,
		PortScansTable,
		SslScansTable,
		TargetsTable,
		TargetIpsTable,
	}
)

func init() {
	CspScansTable.ForeignKeys[0].RefTable = TargetsTable
	PortsTable.ForeignKeys[0].RefTable = PortScansTable
	PortScansTable.ForeignKeys[0].RefTable = IpsTable
	SslScansTable.ForeignKeys[0].RefTable = TargetsTable
	TargetIpsTable.ForeignKeys[0].RefTable = TargetsTable
	TargetIpsTable.ForeignKeys[1].RefTable = IpsTable
}
