// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PortsColumns holds the columns for the "ports" table.
	PortsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeInt},
		{Name: "port_scan_ports", Type: field.TypeInt},
	}
	// PortsTable holds the schema information for the "ports" table.
	PortsTable = &schema.Table{
		Name:       "ports",
		Columns:    PortsColumns,
		PrimaryKey: []*schema.Column{PortsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ports_port_scans_ports",
				Columns:    []*schema.Column{PortsColumns[2]},
				RefColumns: []*schema.Column{PortScansColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PortScansColumns holds the columns for the "port_scans" table.
	PortScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "target_scans", Type: field.TypeInt},
	}
	// PortScansTable holds the schema information for the "port_scans" table.
	PortScansTable = &schema.Table{
		Name:       "port_scans",
		Columns:    PortScansColumns,
		PrimaryKey: []*schema.Column{PortScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "port_scans_targets_scans",
				Columns:    []*schema.Column{PortScansColumns[2]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SslScansColumns holds the columns for the "ssl_scans" table.
	SslScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "grade", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "cert_issuer", Type: field.TypeString, Nullable: true},
		{Name: "cert_subject", Type: field.TypeString, Nullable: true},
		{Name: "cert_expiry", Type: field.TypeTime, Nullable: true},
		{Name: "protocols", Type: field.TypeJSON, Nullable: true},
		{Name: "vulnerabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "target_ssl_scans", Type: field.TypeInt},
	}
	// SslScansTable holds the schema information for the "ssl_scans" table.
	SslScansTable = &schema.Table{
		Name:       "ssl_scans",
		Columns:    SslScansColumns,
		PrimaryKey: []*schema.Column{SslScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ssl_scans_targets_ssl_scans",
				Columns:    []*schema.Column{SslScansColumns[9]},
				RefColumns: []*schema.Column{TargetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "input", Type: field.TypeString, Unique: true},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PortsTable,
		PortScansTable,
		SslScansTable,
		TargetsTable,
	}
)

func init() {
	PortsTable.ForeignKeys[0].RefTable = PortScansTable
	PortScansTable.ForeignKeys[0].RefTable = TargetsTable
	SslScansTable.ForeignKeys[0].RefTable = TargetsTable
}
