// Code generated by ent, DO NOT EDIT.

package sslscan

import (
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldID, id))
}

// ScannedAt applies equality check predicate on the "scanned_at" field. It's identical to ScannedAtEQ.
func ScannedAt(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldScannedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// CheckCount applies equality check predicate on the "check_count" field. It's identical to CheckCountEQ.
func CheckCount(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCheckCount, v))
}

// Grade applies equality check predicate on the "grade" field. It's identical to GradeEQ.
func Grade(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldGrade, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldStatus, v))
}

// CertIssuer applies equality check predicate on the "cert_issuer" field. It's identical to CertIssuerEQ.
func CertIssuer(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertIssuer, v))
}

// CertSubject applies equality check predicate on the "cert_subject" field. It's identical to CertSubjectEQ.
func CertSubject(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertSubject, v))
}

// CertExpiry applies equality check predicate on the "cert_expiry" field. It's identical to CertExpiryEQ.
func CertExpiry(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertExpiry, v))
}

// ScannedAtEQ applies the EQ predicate on the "scanned_at" field.
func ScannedAtEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldScannedAt, v))
}

// ScannedAtNEQ applies the NEQ predicate on the "scanned_at" field.
func ScannedAtNEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldScannedAt, v))
}

// ScannedAtIn applies the In predicate on the "scanned_at" field.
func ScannedAtIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldScannedAt, vs...))
}

// ScannedAtNotIn applies the NotIn predicate on the "scanned_at" field.
func ScannedAtNotIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldScannedAt, vs...))
}

// ScannedAtGT applies the GT predicate on the "scanned_at" field.
func ScannedAtGT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldScannedAt, v))
}

// ScannedAtGTE applies the GTE predicate on the "scanned_at" field.
func ScannedAtGTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldScannedAt, v))
}

// ScannedAtLT applies the LT predicate on the "scanned_at" field.
func ScannedAtLT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldScannedAt, v))
}

// ScannedAtLTE applies the LTE predicate on the "scanned_at" field.
func ScannedAtLTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldScannedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldLastSeenAt))
}

// CheckCountEQ applies the EQ predicate on the "check_count" field.
func CheckCountEQ(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCheckCount, v))
}

// CheckCountNEQ applies the NEQ predicate on the "check_count" field.
func CheckCountNEQ(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldCheckCount, v))
}

// CheckCountIn applies the In predicate on the "check_count" field.
func CheckCountIn(vs ...int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldCheckCount, vs...))
}

// CheckCountNotIn applies the NotIn predicate on the "check_count" field.
func CheckCountNotIn(vs ...int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldCheckCount, vs...))
}

// CheckCountGT applies the GT predicate on the "check_count" field.
func CheckCountGT(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldCheckCount, v))
}

// CheckCountGTE applies the GTE predicate on the "check_count" field.
func CheckCountGTE(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldCheckCount, v))
}

// CheckCountLT applies the LT predicate on the "check_count" field.
func CheckCountLT(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldCheckCount, v))
}

// CheckCountLTE applies the LTE predicate on the "check_count" field.
func CheckCountLTE(v int) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldCheckCount, v))
}

// GradeEQ applies the EQ predicate on the "grade" field.
func GradeEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldGrade, v))
}

// GradeNEQ applies the NEQ predicate on the "grade" field.
func GradeNEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldGrade, v))
}

// GradeIn applies the In predicate on the "grade" field.
func GradeIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldGrade, vs...))
}

// GradeNotIn applies the NotIn predicate on the "grade" field.
func GradeNotIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldGrade, vs...))
}

// GradeGT applies the GT predicate on the "grade" field.
func GradeGT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldGrade, v))
}

// GradeGTE applies the GTE predicate on the "grade" field.
func GradeGTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldGrade, v))
}

// GradeLT applies the LT predicate on the "grade" field.
func GradeLT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldGrade, v))
}

// GradeLTE applies the LTE predicate on the "grade" field.
func GradeLTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldGrade, v))
}

// GradeContains applies the Contains predicate on the "grade" field.
func GradeContains(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContains(FieldGrade, v))
}

// GradeHasPrefix applies the HasPrefix predicate on the "grade" field.
func GradeHasPrefix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasPrefix(FieldGrade, v))
}

// GradeHasSuffix applies the HasSuffix predicate on the "grade" field.
func GradeHasSuffix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasSuffix(FieldGrade, v))
}

// GradeEqualFold applies the EqualFold predicate on the "grade" field.
func GradeEqualFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEqualFold(FieldGrade, v))
}

// GradeContainsFold applies the ContainsFold predicate on the "grade" field.
func GradeContainsFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContainsFold(FieldGrade, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContainsFold(FieldStatus, v))
}

// CertIssuerEQ applies the EQ predicate on the "cert_issuer" field.
func CertIssuerEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertIssuer, v))
}

// CertIssuerNEQ applies the NEQ predicate on the "cert_issuer" field.
func CertIssuerNEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldCertIssuer, v))
}

// CertIssuerIn applies the In predicate on the "cert_issuer" field.
func CertIssuerIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldCertIssuer, vs...))
}

// CertIssuerNotIn applies the NotIn predicate on the "cert_issuer" field.
func CertIssuerNotIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldCertIssuer, vs...))
}

// CertIssuerGT applies the GT predicate on the "cert_issuer" field.
func CertIssuerGT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldCertIssuer, v))
}

// CertIssuerGTE applies the GTE predicate on the "cert_issuer" field.
func CertIssuerGTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldCertIssuer, v))
}

// CertIssuerLT applies the LT predicate on the "cert_issuer" field.
func CertIssuerLT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldCertIssuer, v))
}

// CertIssuerLTE applies the LTE predicate on the "cert_issuer" field.
func CertIssuerLTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldCertIssuer, v))
}

// CertIssuerContains applies the Contains predicate on the "cert_issuer" field.
func CertIssuerContains(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContains(FieldCertIssuer, v))
}

// CertIssuerHasPrefix applies the HasPrefix predicate on the "cert_issuer" field.
func CertIssuerHasPrefix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasPrefix(FieldCertIssuer, v))
}

// CertIssuerHasSuffix applies the HasSuffix predicate on the "cert_issuer" field.
func CertIssuerHasSuffix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasSuffix(FieldCertIssuer, v))
}

// CertIssuerIsNil applies the IsNil predicate on the "cert_issuer" field.
func CertIssuerIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldCertIssuer))
}

// CertIssuerNotNil applies the NotNil predicate on the "cert_issuer" field.
func CertIssuerNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldCertIssuer))
}

// CertIssuerEqualFold applies the EqualFold predicate on the "cert_issuer" field.
func CertIssuerEqualFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEqualFold(FieldCertIssuer, v))
}

// CertIssuerContainsFold applies the ContainsFold predicate on the "cert_issuer" field.
func CertIssuerContainsFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContainsFold(FieldCertIssuer, v))
}

// CertSubjectEQ applies the EQ predicate on the "cert_subject" field.
func CertSubjectEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertSubject, v))
}

// CertSubjectNEQ applies the NEQ predicate on the "cert_subject" field.
func CertSubjectNEQ(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldCertSubject, v))
}

// CertSubjectIn applies the In predicate on the "cert_subject" field.
func CertSubjectIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldCertSubject, vs...))
}

// CertSubjectNotIn applies the NotIn predicate on the "cert_subject" field.
func CertSubjectNotIn(vs ...string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldCertSubject, vs...))
}

// CertSubjectGT applies the GT predicate on the "cert_subject" field.
func CertSubjectGT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldCertSubject, v))
}

// CertSubjectGTE applies the GTE predicate on the "cert_subject" field.
func CertSubjectGTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldCertSubject, v))
}

// CertSubjectLT applies the LT predicate on the "cert_subject" field.
func CertSubjectLT(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldCertSubject, v))
}

// CertSubjectLTE applies the LTE predicate on the "cert_subject" field.
func CertSubjectLTE(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldCertSubject, v))
}

// CertSubjectContains applies the Contains predicate on the "cert_subject" field.
func CertSubjectContains(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContains(FieldCertSubject, v))
}

// CertSubjectHasPrefix applies the HasPrefix predicate on the "cert_subject" field.
func CertSubjectHasPrefix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasPrefix(FieldCertSubject, v))
}

// CertSubjectHasSuffix applies the HasSuffix predicate on the "cert_subject" field.
func CertSubjectHasSuffix(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldHasSuffix(FieldCertSubject, v))
}

// CertSubjectIsNil applies the IsNil predicate on the "cert_subject" field.
func CertSubjectIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldCertSubject))
}

// CertSubjectNotNil applies the NotNil predicate on the "cert_subject" field.
func CertSubjectNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldCertSubject))
}

// CertSubjectEqualFold applies the EqualFold predicate on the "cert_subject" field.
func CertSubjectEqualFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEqualFold(FieldCertSubject, v))
}

// CertSubjectContainsFold applies the ContainsFold predicate on the "cert_subject" field.
func CertSubjectContainsFold(v string) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldContainsFold(FieldCertSubject, v))
}

// CertExpiryEQ applies the EQ predicate on the "cert_expiry" field.
func CertExpiryEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldEQ(FieldCertExpiry, v))
}

// CertExpiryNEQ applies the NEQ predicate on the "cert_expiry" field.
func CertExpiryNEQ(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNEQ(FieldCertExpiry, v))
}

// CertExpiryIn applies the In predicate on the "cert_expiry" field.
func CertExpiryIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIn(FieldCertExpiry, vs...))
}

// CertExpiryNotIn applies the NotIn predicate on the "cert_expiry" field.
func CertExpiryNotIn(vs ...time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotIn(FieldCertExpiry, vs...))
}

// CertExpiryGT applies the GT predicate on the "cert_expiry" field.
func CertExpiryGT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGT(FieldCertExpiry, v))
}

// CertExpiryGTE applies the GTE predicate on the "cert_expiry" field.
func CertExpiryGTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldGTE(FieldCertExpiry, v))
}

// CertExpiryLT applies the LT predicate on the "cert_expiry" field.
func CertExpiryLT(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLT(FieldCertExpiry, v))
}

// CertExpiryLTE applies the LTE predicate on the "cert_expiry" field.
func CertExpiryLTE(v time.Time) predicate.SSLScan {
	return predicate.SSLScan(sql.FieldLTE(FieldCertExpiry, v))
}

// CertExpiryIsNil applies the IsNil predicate on the "cert_expiry" field.
func CertExpiryIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldCertExpiry))
}

// CertExpiryNotNil applies the NotNil predicate on the "cert_expiry" field.
func CertExpiryNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldCertExpiry))
}

// ProtocolsIsNil applies the IsNil predicate on the "protocols" field.
func ProtocolsIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldProtocols))
}

// ProtocolsNotNil applies the NotNil predicate on the "protocols" field.
func ProtocolsNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldProtocols))
}

// VulnerabilitiesIsNil applies the IsNil predicate on the "vulnerabilities" field.
func VulnerabilitiesIsNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldIsNull(FieldVulnerabilities))
}

// VulnerabilitiesNotNil applies the NotNil predicate on the "vulnerabilities" field.
func VulnerabilitiesNotNil() predicate.SSLScan {
	return predicate.SSLScan(sql.FieldNotNull(FieldVulnerabilities))
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.SSLScan {
	return predicate.SSLScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.Target) predicate.SSLScan {
	return predicate.SSLScan(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SSLScan) predicate.SSLScan {
	return predicate.SSLScan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SSLScan) predicate.SSLScan {
	return predicate.SSLScan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SSLScan) predicate.SSLScan {
	return predicate.SSLScan(sql.NotPredicates(p))
}
