// Code generated by ent, DO NOT EDIT.

package cspscan

import (
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLTE(FieldID, id))
}

// ScannedAt applies equality check predicate on the "scanned_at" field. It's identical to ScannedAtEQ.
func ScannedAt(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldScannedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// CheckCount applies equality check predicate on the "check_count" field. It's identical to CheckCountEQ.
func CheckCount(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldCheckCount, v))
}

// CspHeader applies equality check predicate on the "csp_header" field. It's identical to CspHeaderEQ.
func CspHeader(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldCspHeader, v))
}

// ScannedAtEQ applies the EQ predicate on the "scanned_at" field.
func ScannedAtEQ(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldScannedAt, v))
}

// ScannedAtNEQ applies the NEQ predicate on the "scanned_at" field.
func ScannedAtNEQ(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNEQ(FieldScannedAt, v))
}

// ScannedAtIn applies the In predicate on the "scanned_at" field.
func ScannedAtIn(vs ...time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIn(FieldScannedAt, vs...))
}

// ScannedAtNotIn applies the NotIn predicate on the "scanned_at" field.
func ScannedAtNotIn(vs ...time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotIn(FieldScannedAt, vs...))
}

// ScannedAtGT applies the GT predicate on the "scanned_at" field.
func ScannedAtGT(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGT(FieldScannedAt, v))
}

// ScannedAtGTE applies the GTE predicate on the "scanned_at" field.
func ScannedAtGTE(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGTE(FieldScannedAt, v))
}

// ScannedAtLT applies the LT predicate on the "scanned_at" field.
func ScannedAtLT(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLT(FieldScannedAt, v))
}

// ScannedAtLTE applies the LTE predicate on the "scanned_at" field.
func ScannedAtLTE(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLTE(FieldScannedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotNull(FieldLastSeenAt))
}

// CheckCountEQ applies the EQ predicate on the "check_count" field.
func CheckCountEQ(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldCheckCount, v))
}

// CheckCountNEQ applies the NEQ predicate on the "check_count" field.
func CheckCountNEQ(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNEQ(FieldCheckCount, v))
}

// CheckCountIn applies the In predicate on the "check_count" field.
func CheckCountIn(vs ...int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIn(FieldCheckCount, vs...))
}

// CheckCountNotIn applies the NotIn predicate on the "check_count" field.
func CheckCountNotIn(vs ...int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotIn(FieldCheckCount, vs...))
}

// CheckCountGT applies the GT predicate on the "check_count" field.
func CheckCountGT(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGT(FieldCheckCount, v))
}

// CheckCountGTE applies the GTE predicate on the "check_count" field.
func CheckCountGTE(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGTE(FieldCheckCount, v))
}

// CheckCountLT applies the LT predicate on the "check_count" field.
func CheckCountLT(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLT(FieldCheckCount, v))
}

// CheckCountLTE applies the LTE predicate on the "check_count" field.
func CheckCountLTE(v int) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLTE(FieldCheckCount, v))
}

// CspHeaderEQ applies the EQ predicate on the "csp_header" field.
func CspHeaderEQ(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEQ(FieldCspHeader, v))
}

// CspHeaderNEQ applies the NEQ predicate on the "csp_header" field.
func CspHeaderNEQ(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNEQ(FieldCspHeader, v))
}

// CspHeaderIn applies the In predicate on the "csp_header" field.
func CspHeaderIn(vs ...string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIn(FieldCspHeader, vs...))
}

// CspHeaderNotIn applies the NotIn predicate on the "csp_header" field.
func CspHeaderNotIn(vs ...string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotIn(FieldCspHeader, vs...))
}

// CspHeaderGT applies the GT predicate on the "csp_header" field.
func CspHeaderGT(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGT(FieldCspHeader, v))
}

// CspHeaderGTE applies the GTE predicate on the "csp_header" field.
func CspHeaderGTE(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldGTE(FieldCspHeader, v))
}

// CspHeaderLT applies the LT predicate on the "csp_header" field.
func CspHeaderLT(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLT(FieldCspHeader, v))
}

// CspHeaderLTE applies the LTE predicate on the "csp_header" field.
func CspHeaderLTE(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldLTE(FieldCspHeader, v))
}

// CspHeaderContains applies the Contains predicate on the "csp_header" field.
func CspHeaderContains(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldContains(FieldCspHeader, v))
}

// CspHeaderHasPrefix applies the HasPrefix predicate on the "csp_header" field.
func CspHeaderHasPrefix(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldHasPrefix(FieldCspHeader, v))
}

// CspHeaderHasSuffix applies the HasSuffix predicate on the "csp_header" field.
func CspHeaderHasSuffix(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldHasSuffix(FieldCspHeader, v))
}

// CspHeaderEqualFold applies the EqualFold predicate on the "csp_header" field.
func CspHeaderEqualFold(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldEqualFold(FieldCspHeader, v))
}

// CspHeaderContainsFold applies the ContainsFold predicate on the "csp_header" field.
func CspHeaderContainsFold(v string) predicate.CSPScan {
	return predicate.CSPScan(sql.FieldContainsFold(FieldCspHeader, v))
}

// FindingsIsNil applies the IsNil predicate on the "findings" field.
func FindingsIsNil() predicate.CSPScan {
	return predicate.CSPScan(sql.FieldIsNull(FieldFindings))
}

// FindingsNotNil applies the NotNil predicate on the "findings" field.
func FindingsNotNil() predicate.CSPScan {
	return predicate.CSPScan(sql.FieldNotNull(FieldFindings))
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.CSPScan {
	return predicate.CSPScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.Target) predicate.CSPScan {
	return predicate.CSPScan(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CSPScan) predicate.CSPScan {
	return predicate.CSPScan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CSPScan) predicate.CSPScan {
	return predicate.CSPScan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CSPScan) predicate.CSPScan {
	return predicate.CSPScan(sql.NotPredicates(p))
}
