// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"perimeter/ent/migrate"

	"perimeter/ent/cspscan"
	"perimeter/ent/datamigration"
	"perimeter/ent/importerconfig"
	"perimeter/ent/invite"
	"perimeter/ent/ip"
	"perimeter/ent/job"
	"perimeter/ent/notifierconfig"
	"perimeter/ent/port"
	"perimeter/ent/portscan"
	"perimeter/ent/session"
	"perimeter/ent/sslscan"
	"perimeter/ent/tag"
	"perimeter/ent/target"
	"perimeter/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CSPScan is the client for interacting with the CSPScan builders.
	CSPScan *CSPScanClient
	// DataMigration is the client for interacting with the DataMigration builders.
	DataMigration *DataMigrationClient
	// IP is the client for interacting with the IP builders.
	IP *IPClient
	// ImporterConfig is the client for interacting with the ImporterConfig builders.
	ImporterConfig *ImporterConfigClient
	// Invite is the client for interacting with the Invite builders.
	Invite *InviteClient
	// Job is the client for interacting with the Job builders.
	Job *JobClient
	// NotifierConfig is the client for interacting with the NotifierConfig builders.
	NotifierConfig *NotifierConfigClient
	// Port is the client for interacting with the Port builders.
	Port *PortClient
	// PortScan is the client for interacting with the PortScan builders.
	PortScan *PortScanClient
	// SSLScan is the client for interacting with the SSLScan builders.
	SSLScan *SSLScanClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// Target is the client for interacting with the Target builders.
	Target *TargetClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CSPScan = NewCSPScanClient(c.config)
	c.DataMigration = NewDataMigrationClient(c.config)
	c.IP = NewIPClient(c.config)
	c.ImporterConfig = NewImporterConfigClient(c.config)
	c.Invite = NewInviteClient(c.config)
	c.Job = NewJobClient(c.config)
	c.NotifierConfig = NewNotifierConfigClient(c.config)
	c.Port = NewPortClient(c.config)
	c.PortScan = NewPortScanClient(c.config)
	c.SSLScan = NewSSLScanClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.Target = NewTargetClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		CSPScan:        NewCSPScanClient(cfg),
		DataMigration:  NewDataMigrationClient(cfg),
		IP:             NewIPClient(cfg),
		ImporterConfig: NewImporterConfigClient(cfg),
		Invite:         NewInviteClient(cfg),
		Job:            NewJobClient(cfg),
		NotifierConfig: NewNotifierConfigClient(cfg),
		Port:           NewPortClient(cfg),
		PortScan:       NewPortScanClient(cfg),
		SSLScan:        NewSSLScanClient(cfg),
		Session:        NewSessionClient(cfg),
		Tag:            NewTagClient(cfg),
		Target:         NewTargetClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		CSPScan:        NewCSPScanClient(cfg),
		DataMigration:  NewDataMigrationClient(cfg),
		IP:             NewIPClient(cfg),
		ImporterConfig: NewImporterConfigClient(cfg),
		Invite:         NewInviteClient(cfg),
		Job:            NewJobClient(cfg),
		NotifierConfig: NewNotifierConfigClient(cfg),
		Port:           NewPortClient(cfg),
		PortScan:       NewPortScanClient(cfg),
		SSLScan:        NewSSLScanClient(cfg),
		Session:        NewSessionClient(cfg),
		Tag:            NewTagClient(cfg),
		Target:         NewTargetClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CSPScan.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CSPScan, c.DataMigration, c.IP, c.ImporterConfig, c.Invite, c.Job,
		c.NotifierConfig, c.Port, c.PortScan, c.SSLScan, c.Session, c.Tag, c.Target,
		c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CSPScan, c.DataMigration, c.IP, c.ImporterConfig, c.Invite, c.Job,
		c.NotifierConfig, c.Port, c.PortScan, c.SSLScan, c.Session, c.Tag, c.Target,
		c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CSPScanMutation:
		return c.CSPScan.mutate(ctx, m)
	case *DataMigrationMutation:
		return c.DataMigration.mutate(ctx, m)
	case *IPMutation:
		return c.IP.mutate(ctx, m)
	case *ImporterConfigMutation:
		return c.ImporterConfig.mutate(ctx, m)
	case *InviteMutation:
		return c.Invite.mutate(ctx, m)
	case *JobMutation:
		return c.Job.mutate(ctx, m)
	case *NotifierConfigMutation:
		return c.NotifierConfig.mutate(ctx, m)
	case *PortMutation:
		return c.Port.mutate(ctx, m)
	case *PortScanMutation:
		return c.PortScan.mutate(ctx, m)
	case *SSLScanMutation:
		return c.SSLScan.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	case *TargetMutation:
		return c.Target.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CSPScanClient is a client for the CSPScan schema.
type CSPScanClient struct {
	config
}

// NewCSPScanClient returns a client for the CSPScan from the given config.
func NewCSPScanClient(c config) *CSPScanClient {
	return &CSPScanClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cspscan.Hooks(f(g(h())))`.
func (c *CSPScanClient) Use(hooks ...Hook) {
	c.hooks.CSPScan = append(c.hooks.CSPScan, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cspscan.Intercept(f(g(h())))`.
func (c *CSPScanClient) Intercept(interceptors ...Interceptor) {
	c.inters.CSPScan = append(c.inters.CSPScan, interceptors...)
}

// Create returns a builder for creating a CSPScan entity.
func (c *CSPScanClient) Create() *CSPScanCreate {
	mutation := newCSPScanMutation(c.config, OpCreate)
	return &CSPScanCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CSPScan entities.
func (c *CSPScanClient) CreateBulk(builders ...*CSPScanCreate) *CSPScanCreateBulk {
	return &CSPScanCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CSPScanClient) MapCreateBulk(slice any, setFunc func(*CSPScanCreate, int)) *CSPScanCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CSPScanCreateBulk{err: fmt.Errorf("calling to CSPScanClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CSPScanCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CSPScanCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CSPScan.
func (c *CSPScanClient) Update() *CSPScanUpdate {
	mutation := newCSPScanMutation(c.config, OpUpdate)
	return &CSPScanUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CSPScanClient) UpdateOne(_m *CSPScan) *CSPScanUpdateOne {
	mutation := newCSPScanMutation(c.config, OpUpdateOne, withCSPScan(_m))
	return &CSPScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CSPScanClient) UpdateOneID(id int) *CSPScanUpdateOne {
	mutation := newCSPScanMutation(c.config, OpUpdateOne, withCSPScanID(id))
	return &CSPScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CSPScan.
func (c *CSPScanClient) Delete() *CSPScanDelete {
	mutation := newCSPScanMutation(c.config, OpDelete)
	return &CSPScanDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CSPScanClient) DeleteOne(_m *CSPScan) *CSPScanDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CSPScanClient) DeleteOneID(id int) *CSPScanDeleteOne {
	builder := c.Delete().Where(cspscan.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CSPScanDeleteOne{builder}
}

// Query returns a query builder for CSPScan.
func (c *CSPScanClient) Query() *CSPScanQuery {
	return &CSPScanQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCSPScan},
		inters: c.Interceptors(),
	}
}

// Get returns a CSPScan entity by its id.
func (c *CSPScanClient) Get(ctx context.Context, id int) (*CSPScan, error) {
	return c.Query().Where(cspscan.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CSPScanClient) GetX(ctx context.Context, id int) *CSPScan {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTarget queries the target edge of a CSPScan.
func (c *CSPScanClient) QueryTarget(_m *CSPScan) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(cspscan.Table, cspscan.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cspscan.TargetTable, cspscan.TargetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CSPScanClient) Hooks() []Hook {
	return c.hooks.CSPScan
}

// Interceptors returns the client interceptors.
func (c *CSPScanClient) Interceptors() []Interceptor {
	return c.inters.CSPScan
}

func (c *CSPScanClient) mutate(ctx context.Context, m *CSPScanMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CSPScanCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CSPScanUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CSPScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CSPScanDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CSPScan mutation op: %q", m.Op())
	}
}

// DataMigrationClient is a client for the DataMigration schema.
type DataMigrationClient struct {
	config
}

// NewDataMigrationClient returns a client for the DataMigration from the given config.
func NewDataMigrationClient(c config) *DataMigrationClient {
	return &DataMigrationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `datamigration.Hooks(f(g(h())))`.
func (c *DataMigrationClient) Use(hooks ...Hook) {
	c.hooks.DataMigration = append(c.hooks.DataMigration, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `datamigration.Intercept(f(g(h())))`.
func (c *DataMigrationClient) Intercept(interceptors ...Interceptor) {
	c.inters.DataMigration = append(c.inters.DataMigration, interceptors...)
}

// Create returns a builder for creating a DataMigration entity.
func (c *DataMigrationClient) Create() *DataMigrationCreate {
	mutation := newDataMigrationMutation(c.config, OpCreate)
	return &DataMigrationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DataMigration entities.
func (c *DataMigrationClient) CreateBulk(builders ...*DataMigrationCreate) *DataMigrationCreateBulk {
	return &DataMigrationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DataMigrationClient) MapCreateBulk(slice any, setFunc func(*DataMigrationCreate, int)) *DataMigrationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DataMigrationCreateBulk{err: fmt.Errorf("calling to DataMigrationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DataMigrationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DataMigrationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DataMigration.
func (c *DataMigrationClient) Update() *DataMigrationUpdate {
	mutation := newDataMigrationMutation(c.config, OpUpdate)
	return &DataMigrationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DataMigrationClient) UpdateOne(_m *DataMigration) *DataMigrationUpdateOne {
	mutation := newDataMigrationMutation(c.config, OpUpdateOne, withDataMigration(_m))
	return &DataMigrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DataMigrationClient) UpdateOneID(id int) *DataMigrationUpdateOne {
	mutation := newDataMigrationMutation(c.config, OpUpdateOne, withDataMigrationID(id))
	return &DataMigrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DataMigration.
func (c *DataMigrationClient) Delete() *DataMigrationDelete {
	mutation := newDataMigrationMutation(c.config, OpDelete)
	return &DataMigrationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DataMigrationClient) DeleteOne(_m *DataMigration) *DataMigrationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DataMigrationClient) DeleteOneID(id int) *DataMigrationDeleteOne {
	builder := c.Delete().Where(datamigration.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DataMigrationDeleteOne{builder}
}

// Query returns a query builder for DataMigration.
func (c *DataMigrationClient) Query() *DataMigrationQuery {
	return &DataMigrationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDataMigration},
		inters: c.Interceptors(),
	}
}

// Get returns a DataMigration entity by its id.
func (c *DataMigrationClient) Get(ctx context.Context, id int) (*DataMigration, error) {
	return c.Query().Where(datamigration.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DataMigrationClient) GetX(ctx context.Context, id int) *DataMigration {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DataMigrationClient) Hooks() []Hook {
	return c.hooks.DataMigration
}

// Interceptors returns the client interceptors.
func (c *DataMigrationClient) Interceptors() []Interceptor {
	return c.inters.DataMigration
}

func (c *DataMigrationClient) mutate(ctx context.Context, m *DataMigrationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DataMigrationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DataMigrationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DataMigrationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DataMigrationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DataMigration mutation op: %q", m.Op())
	}
}

// IPClient is a client for the IP schema.
type IPClient struct {
	config
}

// NewIPClient returns a client for the IP from the given config.
func NewIPClient(c config) *IPClient {
	return &IPClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ip.Hooks(f(g(h())))`.
func (c *IPClient) Use(hooks ...Hook) {
	c.hooks.IP = append(c.hooks.IP, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ip.Intercept(f(g(h())))`.
func (c *IPClient) Intercept(interceptors ...Interceptor) {
	c.inters.IP = append(c.inters.IP, interceptors...)
}

// Create returns a builder for creating a IP entity.
func (c *IPClient) Create() *IPCreate {
	mutation := newIPMutation(c.config, OpCreate)
	return &IPCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IP entities.
func (c *IPClient) CreateBulk(builders ...*IPCreate) *IPCreateBulk {
	return &IPCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IPClient) MapCreateBulk(slice any, setFunc func(*IPCreate, int)) *IPCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IPCreateBulk{err: fmt.Errorf("calling to IPClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IPCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IPCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IP.
func (c *IPClient) Update() *IPUpdate {
	mutation := newIPMutation(c.config, OpUpdate)
	return &IPUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IPClient) UpdateOne(_m *IP) *IPUpdateOne {
	mutation := newIPMutation(c.config, OpUpdateOne, withIP(_m))
	return &IPUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IPClient) UpdateOneID(id int) *IPUpdateOne {
	mutation := newIPMutation(c.config, OpUpdateOne, withIPID(id))
	return &IPUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IP.
func (c *IPClient) Delete() *IPDelete {
	mutation := newIPMutation(c.config, OpDelete)
	return &IPDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IPClient) DeleteOne(_m *IP) *IPDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IPClient) DeleteOneID(id int) *IPDeleteOne {
	builder := c.Delete().Where(ip.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IPDeleteOne{builder}
}

// Query returns a query builder for IP.
func (c *IPClient) Query() *IPQuery {
	return &IPQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIP},
		inters: c.Interceptors(),
	}
}

// Get returns a IP entity by its id.
func (c *IPClient) Get(ctx context.Context, id int) (*IP, error) {
	return c.Query().Where(ip.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IPClient) GetX(ctx context.Context, id int) *IP {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTargets queries the targets edge of a IP.
func (c *IPClient) QueryTargets(_m *IP) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ip.Table, ip.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ip.TargetsTable, ip.TargetsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryScans queries the scans edge of a IP.
func (c *IPClient) QueryScans(_m *IP) *PortScanQuery {
	query := (&PortScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ip.Table, ip.FieldID, id),
			sqlgraph.To(portscan.Table, portscan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ip.ScansTable, ip.ScansColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IPClient) Hooks() []Hook {
	return c.hooks.IP
}

// Interceptors returns the client interceptors.
func (c *IPClient) Interceptors() []Interceptor {
	return c.inters.IP
}

func (c *IPClient) mutate(ctx context.Context, m *IPMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IPCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IPUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IPUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IPDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IP mutation op: %q", m.Op())
	}
}

// ImporterConfigClient is a client for the ImporterConfig schema.
type ImporterConfigClient struct {
	config
}

// NewImporterConfigClient returns a client for the ImporterConfig from the given config.
func NewImporterConfigClient(c config) *ImporterConfigClient {
	return &ImporterConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `importerconfig.Hooks(f(g(h())))`.
func (c *ImporterConfigClient) Use(hooks ...Hook) {
	c.hooks.ImporterConfig = append(c.hooks.ImporterConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `importerconfig.Intercept(f(g(h())))`.
func (c *ImporterConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.ImporterConfig = append(c.inters.ImporterConfig, interceptors...)
}

// Create returns a builder for creating a ImporterConfig entity.
func (c *ImporterConfigClient) Create() *ImporterConfigCreate {
	mutation := newImporterConfigMutation(c.config, OpCreate)
	return &ImporterConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ImporterConfig entities.
func (c *ImporterConfigClient) CreateBulk(builders ...*ImporterConfigCreate) *ImporterConfigCreateBulk {
	return &ImporterConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ImporterConfigClient) MapCreateBulk(slice any, setFunc func(*ImporterConfigCreate, int)) *ImporterConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ImporterConfigCreateBulk{err: fmt.Errorf("calling to ImporterConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ImporterConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ImporterConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ImporterConfig.
func (c *ImporterConfigClient) Update() *ImporterConfigUpdate {
	mutation := newImporterConfigMutation(c.config, OpUpdate)
	return &ImporterConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ImporterConfigClient) UpdateOne(_m *ImporterConfig) *ImporterConfigUpdateOne {
	mutation := newImporterConfigMutation(c.config, OpUpdateOne, withImporterConfig(_m))
	return &ImporterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ImporterConfigClient) UpdateOneID(id int) *ImporterConfigUpdateOne {
	mutation := newImporterConfigMutation(c.config, OpUpdateOne, withImporterConfigID(id))
	return &ImporterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ImporterConfig.
func (c *ImporterConfigClient) Delete() *ImporterConfigDelete {
	mutation := newImporterConfigMutation(c.config, OpDelete)
	return &ImporterConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ImporterConfigClient) DeleteOne(_m *ImporterConfig) *ImporterConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ImporterConfigClient) DeleteOneID(id int) *ImporterConfigDeleteOne {
	builder := c.Delete().Where(importerconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ImporterConfigDeleteOne{builder}
}

// Query returns a query builder for ImporterConfig.
func (c *ImporterConfigClient) Query() *ImporterConfigQuery {
	return &ImporterConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeImporterConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a ImporterConfig entity by its id.
func (c *ImporterConfigClient) Get(ctx context.Context, id int) (*ImporterConfig, error) {
	return c.Query().Where(importerconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ImporterConfigClient) GetX(ctx context.Context, id int) *ImporterConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ImporterConfigClient) Hooks() []Hook {
	return c.hooks.ImporterConfig
}

// Interceptors returns the client interceptors.
func (c *ImporterConfigClient) Interceptors() []Interceptor {
	return c.inters.ImporterConfig
}

func (c *ImporterConfigClient) mutate(ctx context.Context, m *ImporterConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ImporterConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ImporterConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ImporterConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ImporterConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ImporterConfig mutation op: %q", m.Op())
	}
}

// InviteClient is a client for the Invite schema.
type InviteClient struct {
	config
}

// NewInviteClient returns a client for the Invite from the given config.
func NewInviteClient(c config) *InviteClient {
	return &InviteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invite.Hooks(f(g(h())))`.
func (c *InviteClient) Use(hooks ...Hook) {
	c.hooks.Invite = append(c.hooks.Invite, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invite.Intercept(f(g(h())))`.
func (c *InviteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Invite = append(c.inters.Invite, interceptors...)
}

// Create returns a builder for creating a Invite entity.
func (c *InviteClient) Create() *InviteCreate {
	mutation := newInviteMutation(c.config, OpCreate)
	return &InviteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Invite entities.
func (c *InviteClient) CreateBulk(builders ...*InviteCreate) *InviteCreateBulk {
	return &InviteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InviteClient) MapCreateBulk(slice any, setFunc func(*InviteCreate, int)) *InviteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InviteCreateBulk{err: fmt.Errorf("calling to InviteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InviteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InviteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Invite.
func (c *InviteClient) Update() *InviteUpdate {
	mutation := newInviteMutation(c.config, OpUpdate)
	return &InviteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InviteClient) UpdateOne(_m *Invite) *InviteUpdateOne {
	mutation := newInviteMutation(c.config, OpUpdateOne, withInvite(_m))
	return &InviteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InviteClient) UpdateOneID(id int) *InviteUpdateOne {
	mutation := newInviteMutation(c.config, OpUpdateOne, withInviteID(id))
	return &InviteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Invite.
func (c *InviteClient) Delete() *InviteDelete {
	mutation := newInviteMutation(c.config, OpDelete)
	return &InviteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InviteClient) DeleteOne(_m *Invite) *InviteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InviteClient) DeleteOneID(id int) *InviteDeleteOne {
	builder := c.Delete().Where(invite.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InviteDeleteOne{builder}
}

// Query returns a query builder for Invite.
func (c *InviteClient) Query() *InviteQuery {
	return &InviteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvite},
		inters: c.Interceptors(),
	}
}

// Get returns a Invite entity by its id.
func (c *InviteClient) Get(ctx context.Context, id int) (*Invite, error) {
	return c.Query().Where(invite.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InviteClient) GetX(ctx context.Context, id int) *Invite {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInvitedBy queries the invited_by edge of a Invite.
func (c *InviteClient) QueryInvitedBy(_m *Invite) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invite.Table, invite.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invite.InvitedByTable, invite.InvitedByColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InviteClient) Hooks() []Hook {
	return c.hooks.Invite
}

// Interceptors returns the client interceptors.
func (c *InviteClient) Interceptors() []Interceptor {
	return c.inters.Invite
}

func (c *InviteClient) mutate(ctx context.Context, m *InviteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InviteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InviteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InviteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InviteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Invite mutation op: %q", m.Op())
	}
}

// JobClient is a client for the Job schema.
type JobClient struct {
	config
}

// NewJobClient returns a client for the Job from the given config.
func NewJobClient(c config) *JobClient {
	return &JobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `job.Hooks(f(g(h())))`.
func (c *JobClient) Use(hooks ...Hook) {
	c.hooks.Job = append(c.hooks.Job, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `job.Intercept(f(g(h())))`.
func (c *JobClient) Intercept(interceptors ...Interceptor) {
	c.inters.Job = append(c.inters.Job, interceptors...)
}

// Create returns a builder for creating a Job entity.
func (c *JobClient) Create() *JobCreate {
	mutation := newJobMutation(c.config, OpCreate)
	return &JobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Job entities.
func (c *JobClient) CreateBulk(builders ...*JobCreate) *JobCreateBulk {
	return &JobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobClient) MapCreateBulk(slice any, setFunc func(*JobCreate, int)) *JobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobCreateBulk{err: fmt.Errorf("calling to JobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Job.
func (c *JobClient) Update() *JobUpdate {
	mutation := newJobMutation(c.config, OpUpdate)
	return &JobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobClient) UpdateOne(_m *Job) *JobUpdateOne {
	mutation := newJobMutation(c.config, OpUpdateOne, withJob(_m))
	return &JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobClient) UpdateOneID(id int) *JobUpdateOne {
	mutation := newJobMutation(c.config, OpUpdateOne, withJobID(id))
	return &JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Job.
func (c *JobClient) Delete() *JobDelete {
	mutation := newJobMutation(c.config, OpDelete)
	return &JobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobClient) DeleteOne(_m *Job) *JobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobClient) DeleteOneID(id int) *JobDeleteOne {
	builder := c.Delete().Where(job.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobDeleteOne{builder}
}

// Query returns a query builder for Job.
func (c *JobClient) Query() *JobQuery {
	return &JobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJob},
		inters: c.Interceptors(),
	}
}

// Get returns a Job entity by its id.
func (c *JobClient) Get(ctx context.Context, id int) (*Job, error) {
	return c.Query().Where(job.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobClient) GetX(ctx context.Context, id int) *Job {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobClient) Hooks() []Hook {
	return c.hooks.Job
}

// Interceptors returns the client interceptors.
func (c *JobClient) Interceptors() []Interceptor {
	return c.inters.Job
}

func (c *JobClient) mutate(ctx context.Context, m *JobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Job mutation op: %q", m.Op())
	}
}

// NotifierConfigClient is a client for the NotifierConfig schema.
type NotifierConfigClient struct {
	config
}

// NewNotifierConfigClient returns a client for the NotifierConfig from the given config.
func NewNotifierConfigClient(c config) *NotifierConfigClient {
	return &NotifierConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notifierconfig.Hooks(f(g(h())))`.
func (c *NotifierConfigClient) Use(hooks ...Hook) {
	c.hooks.NotifierConfig = append(c.hooks.NotifierConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notifierconfig.Intercept(f(g(h())))`.
func (c *NotifierConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotifierConfig = append(c.inters.NotifierConfig, interceptors...)
}

// Create returns a builder for creating a NotifierConfig entity.
func (c *NotifierConfigClient) Create() *NotifierConfigCreate {
	mutation := newNotifierConfigMutation(c.config, OpCreate)
	return &NotifierConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotifierConfig entities.
func (c *NotifierConfigClient) CreateBulk(builders ...*NotifierConfigCreate) *NotifierConfigCreateBulk {
	return &NotifierConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotifierConfigClient) MapCreateBulk(slice any, setFunc func(*NotifierConfigCreate, int)) *NotifierConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotifierConfigCreateBulk{err: fmt.Errorf("calling to NotifierConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotifierConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotifierConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotifierConfig.
func (c *NotifierConfigClient) Update() *NotifierConfigUpdate {
	mutation := newNotifierConfigMutation(c.config, OpUpdate)
	return &NotifierConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotifierConfigClient) UpdateOne(_m *NotifierConfig) *NotifierConfigUpdateOne {
	mutation := newNotifierConfigMutation(c.config, OpUpdateOne, withNotifierConfig(_m))
	return &NotifierConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotifierConfigClient) UpdateOneID(id int) *NotifierConfigUpdateOne {
	mutation := newNotifierConfigMutation(c.config, OpUpdateOne, withNotifierConfigID(id))
	return &NotifierConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotifierConfig.
func (c *NotifierConfigClient) Delete() *NotifierConfigDelete {
	mutation := newNotifierConfigMutation(c.config, OpDelete)
	return &NotifierConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotifierConfigClient) DeleteOne(_m *NotifierConfig) *NotifierConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotifierConfigClient) DeleteOneID(id int) *NotifierConfigDeleteOne {
	builder := c.Delete().Where(notifierconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotifierConfigDeleteOne{builder}
}

// Query returns a query builder for NotifierConfig.
func (c *NotifierConfigClient) Query() *NotifierConfigQuery {
	return &NotifierConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotifierConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a NotifierConfig entity by its id.
func (c *NotifierConfigClient) Get(ctx context.Context, id int) (*NotifierConfig, error) {
	return c.Query().Where(notifierconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotifierConfigClient) GetX(ctx context.Context, id int) *NotifierConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotifierConfigClient) Hooks() []Hook {
	return c.hooks.NotifierConfig
}

// Interceptors returns the client interceptors.
func (c *NotifierConfigClient) Interceptors() []Interceptor {
	return c.inters.NotifierConfig
}

func (c *NotifierConfigClient) mutate(ctx context.Context, m *NotifierConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotifierConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotifierConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotifierConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotifierConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotifierConfig mutation op: %q", m.Op())
	}
}

// PortClient is a client for the Port schema.
type PortClient struct {
	config
}

// NewPortClient returns a client for the Port from the given config.
func NewPortClient(c config) *PortClient {
	return &PortClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `port.Hooks(f(g(h())))`.
func (c *PortClient) Use(hooks ...Hook) {
	c.hooks.Port = append(c.hooks.Port, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `port.Intercept(f(g(h())))`.
func (c *PortClient) Intercept(interceptors ...Interceptor) {
	c.inters.Port = append(c.inters.Port, interceptors...)
}

// Create returns a builder for creating a Port entity.
func (c *PortClient) Create() *PortCreate {
	mutation := newPortMutation(c.config, OpCreate)
	return &PortCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Port entities.
func (c *PortClient) CreateBulk(builders ...*PortCreate) *PortCreateBulk {
	return &PortCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PortClient) MapCreateBulk(slice any, setFunc func(*PortCreate, int)) *PortCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PortCreateBulk{err: fmt.Errorf("calling to PortClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PortCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PortCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Port.
func (c *PortClient) Update() *PortUpdate {
	mutation := newPortMutation(c.config, OpUpdate)
	return &PortUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PortClient) UpdateOne(_m *Port) *PortUpdateOne {
	mutation := newPortMutation(c.config, OpUpdateOne, withPort(_m))
	return &PortUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PortClient) UpdateOneID(id int) *PortUpdateOne {
	mutation := newPortMutation(c.config, OpUpdateOne, withPortID(id))
	return &PortUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Port.
func (c *PortClient) Delete() *PortDelete {
	mutation := newPortMutation(c.config, OpDelete)
	return &PortDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PortClient) DeleteOne(_m *Port) *PortDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PortClient) DeleteOneID(id int) *PortDeleteOne {
	builder := c.Delete().Where(port.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PortDeleteOne{builder}
}

// Query returns a query builder for Port.
func (c *PortClient) Query() *PortQuery {
	return &PortQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePort},
		inters: c.Interceptors(),
	}
}

// Get returns a Port entity by its id.
func (c *PortClient) Get(ctx context.Context, id int) (*Port, error) {
	return c.Query().Where(port.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PortClient) GetX(ctx context.Context, id int) *Port {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryScan queries the scan edge of a Port.
func (c *PortClient) QueryScan(_m *Port) *PortScanQuery {
	query := (&PortScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(port.Table, port.FieldID, id),
			sqlgraph.To(portscan.Table, portscan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, port.ScanTable, port.ScanColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PortClient) Hooks() []Hook {
	return c.hooks.Port
}

// Interceptors returns the client interceptors.
func (c *PortClient) Interceptors() []Interceptor {
	return c.inters.Port
}

func (c *PortClient) mutate(ctx context.Context, m *PortMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PortCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PortUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PortUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PortDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Port mutation op: %q", m.Op())
	}
}

// PortScanClient is a client for the PortScan schema.
type PortScanClient struct {
	config
}

// NewPortScanClient returns a client for the PortScan from the given config.
func NewPortScanClient(c config) *PortScanClient {
	return &PortScanClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `portscan.Hooks(f(g(h())))`.
func (c *PortScanClient) Use(hooks ...Hook) {
	c.hooks.PortScan = append(c.hooks.PortScan, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `portscan.Intercept(f(g(h())))`.
func (c *PortScanClient) Intercept(interceptors ...Interceptor) {
	c.inters.PortScan = append(c.inters.PortScan, interceptors...)
}

// Create returns a builder for creating a PortScan entity.
func (c *PortScanClient) Create() *PortScanCreate {
	mutation := newPortScanMutation(c.config, OpCreate)
	return &PortScanCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PortScan entities.
func (c *PortScanClient) CreateBulk(builders ...*PortScanCreate) *PortScanCreateBulk {
	return &PortScanCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PortScanClient) MapCreateBulk(slice any, setFunc func(*PortScanCreate, int)) *PortScanCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PortScanCreateBulk{err: fmt.Errorf("calling to PortScanClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PortScanCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PortScanCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PortScan.
func (c *PortScanClient) Update() *PortScanUpdate {
	mutation := newPortScanMutation(c.config, OpUpdate)
	return &PortScanUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PortScanClient) UpdateOne(_m *PortScan) *PortScanUpdateOne {
	mutation := newPortScanMutation(c.config, OpUpdateOne, withPortScan(_m))
	return &PortScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PortScanClient) UpdateOneID(id int) *PortScanUpdateOne {
	mutation := newPortScanMutation(c.config, OpUpdateOne, withPortScanID(id))
	return &PortScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PortScan.
func (c *PortScanClient) Delete() *PortScanDelete {
	mutation := newPortScanMutation(c.config, OpDelete)
	return &PortScanDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PortScanClient) DeleteOne(_m *PortScan) *PortScanDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PortScanClient) DeleteOneID(id int) *PortScanDeleteOne {
	builder := c.Delete().Where(portscan.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PortScanDeleteOne{builder}
}

// Query returns a query builder for PortScan.
func (c *PortScanClient) Query() *PortScanQuery {
	return &PortScanQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePortScan},
		inters: c.Interceptors(),
	}
}

// Get returns a PortScan entity by its id.
func (c *PortScanClient) Get(ctx context.Context, id int) (*PortScan, error) {
	return c.Query().Where(portscan.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PortScanClient) GetX(ctx context.Context, id int) *PortScan {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIP queries the ip edge of a PortScan.
func (c *PortScanClient) QueryIP(_m *PortScan) *IPQuery {
	query := (&IPClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(portscan.Table, portscan.FieldID, id),
			sqlgraph.To(ip.Table, ip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, portscan.IPTable, portscan.IPColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPorts queries the ports edge of a PortScan.
func (c *PortScanClient) QueryPorts(_m *PortScan) *PortQuery {
	query := (&PortClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(portscan.Table, portscan.FieldID, id),
			sqlgraph.To(port.Table, port.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, portscan.PortsTable, portscan.PortsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PortScanClient) Hooks() []Hook {
	return c.hooks.PortScan
}

// Interceptors returns the client interceptors.
func (c *PortScanClient) Interceptors() []Interceptor {
	return c.inters.PortScan
}

func (c *PortScanClient) mutate(ctx context.Context, m *PortScanMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PortScanCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PortScanUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PortScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PortScanDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PortScan mutation op: %q", m.Op())
	}
}

// SSLScanClient is a client for the SSLScan schema.
type SSLScanClient struct {
	config
}

// NewSSLScanClient returns a client for the SSLScan from the given config.
func NewSSLScanClient(c config) *SSLScanClient {
	return &SSLScanClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sslscan.Hooks(f(g(h())))`.
func (c *SSLScanClient) Use(hooks ...Hook) {
	c.hooks.SSLScan = append(c.hooks.SSLScan, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sslscan.Intercept(f(g(h())))`.
func (c *SSLScanClient) Intercept(interceptors ...Interceptor) {
	c.inters.SSLScan = append(c.inters.SSLScan, interceptors...)
}

// Create returns a builder for creating a SSLScan entity.
func (c *SSLScanClient) Create() *SSLScanCreate {
	mutation := newSSLScanMutation(c.config, OpCreate)
	return &SSLScanCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SSLScan entities.
func (c *SSLScanClient) CreateBulk(builders ...*SSLScanCreate) *SSLScanCreateBulk {
	return &SSLScanCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SSLScanClient) MapCreateBulk(slice any, setFunc func(*SSLScanCreate, int)) *SSLScanCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SSLScanCreateBulk{err: fmt.Errorf("calling to SSLScanClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SSLScanCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SSLScanCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SSLScan.
func (c *SSLScanClient) Update() *SSLScanUpdate {
	mutation := newSSLScanMutation(c.config, OpUpdate)
	return &SSLScanUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SSLScanClient) UpdateOne(_m *SSLScan) *SSLScanUpdateOne {
	mutation := newSSLScanMutation(c.config, OpUpdateOne, withSSLScan(_m))
	return &SSLScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SSLScanClient) UpdateOneID(id int) *SSLScanUpdateOne {
	mutation := newSSLScanMutation(c.config, OpUpdateOne, withSSLScanID(id))
	return &SSLScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SSLScan.
func (c *SSLScanClient) Delete() *SSLScanDelete {
	mutation := newSSLScanMutation(c.config, OpDelete)
	return &SSLScanDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SSLScanClient) DeleteOne(_m *SSLScan) *SSLScanDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SSLScanClient) DeleteOneID(id int) *SSLScanDeleteOne {
	builder := c.Delete().Where(sslscan.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SSLScanDeleteOne{builder}
}

// Query returns a query builder for SSLScan.
func (c *SSLScanClient) Query() *SSLScanQuery {
	return &SSLScanQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSSLScan},
		inters: c.Interceptors(),
	}
}

// Get returns a SSLScan entity by its id.
func (c *SSLScanClient) Get(ctx context.Context, id int) (*SSLScan, error) {
	return c.Query().Where(sslscan.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SSLScanClient) GetX(ctx context.Context, id int) *SSLScan {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTarget queries the target edge of a SSLScan.
func (c *SSLScanClient) QueryTarget(_m *SSLScan) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sslscan.Table, sslscan.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sslscan.TargetTable, sslscan.TargetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SSLScanClient) Hooks() []Hook {
	return c.hooks.SSLScan
}

// Interceptors returns the client interceptors.
func (c *SSLScanClient) Interceptors() []Interceptor {
	return c.inters.SSLScan
}

func (c *SSLScanClient) mutate(ctx context.Context, m *SSLScanMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SSLScanCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SSLScanUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SSLScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SSLScanDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SSLScan mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id int) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id int) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id int) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id int) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Session.
func (c *SessionClient) QueryUser(_m *Session) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, session.UserTable, session.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id int) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id int) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id int) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id int) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTargets queries the targets edge of a Tag.
func (c *TagClient) QueryTargets(_m *Tag) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.TargetsTable, tag.TargetsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// TargetClient is a client for the Target schema.
type TargetClient struct {
	config
}

// NewTargetClient returns a client for the Target from the given config.
func NewTargetClient(c config) *TargetClient {
	return &TargetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `target.Hooks(f(g(h())))`.
func (c *TargetClient) Use(hooks ...Hook) {
	c.hooks.Target = append(c.hooks.Target, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `target.Intercept(f(g(h())))`.
func (c *TargetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Target = append(c.inters.Target, interceptors...)
}

// Create returns a builder for creating a Target entity.
func (c *TargetClient) Create() *TargetCreate {
	mutation := newTargetMutation(c.config, OpCreate)
	return &TargetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Target entities.
func (c *TargetClient) CreateBulk(builders ...*TargetCreate) *TargetCreateBulk {
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TargetClient) MapCreateBulk(slice any, setFunc func(*TargetCreate, int)) *TargetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TargetCreateBulk{err: fmt.Errorf("calling to TargetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TargetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TargetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Target.
func (c *TargetClient) Update() *TargetUpdate {
	mutation := newTargetMutation(c.config, OpUpdate)
	return &TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TargetClient) UpdateOne(_m *Target) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTarget(_m))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TargetClient) UpdateOneID(id int) *TargetUpdateOne {
	mutation := newTargetMutation(c.config, OpUpdateOne, withTargetID(id))
	return &TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Target.
func (c *TargetClient) Delete() *TargetDelete {
	mutation := newTargetMutation(c.config, OpDelete)
	return &TargetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TargetClient) DeleteOne(_m *Target) *TargetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TargetClient) DeleteOneID(id int) *TargetDeleteOne {
	builder := c.Delete().Where(target.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TargetDeleteOne{builder}
}

// Query returns a query builder for Target.
func (c *TargetClient) Query() *TargetQuery {
	return &TargetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTarget},
		inters: c.Interceptors(),
	}
}

// Get returns a Target entity by its id.
func (c *TargetClient) Get(ctx context.Context, id int) (*Target, error) {
	return c.Query().Where(target.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TargetClient) GetX(ctx context.Context, id int) *Target {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIps queries the ips edge of a Target.
func (c *TargetClient) QueryIps(_m *Target) *IPQuery {
	query := (&IPClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(ip.Table, ip.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, target.IpsTable, target.IpsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySslScans queries the ssl_scans edge of a Target.
func (c *TargetClient) QuerySslScans(_m *Target) *SSLScanQuery {
	query := (&SSLScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(sslscan.Table, sslscan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, target.SslScansTable, target.SslScansColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCspScans queries the csp_scans edge of a Target.
func (c *TargetClient) QueryCspScans(_m *Target) *CSPScanQuery {
	query := (&CSPScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(cspscan.Table, cspscan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, target.CspScansTable, target.CspScansColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwner queries the owner edge of a Target.
func (c *TargetClient) QueryOwner(_m *Target) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, target.OwnerTable, target.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Target.
func (c *TargetClient) QueryTags(_m *Target) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(target.Table, target.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, target.TagsTable, target.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TargetClient) Hooks() []Hook {
	return c.hooks.Target
}

// Interceptors returns the client interceptors.
func (c *TargetClient) Interceptors() []Interceptor {
	return c.inters.Target
}

func (c *TargetClient) mutate(ctx context.Context, m *TargetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TargetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TargetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TargetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Target mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTargets queries the targets edge of a User.
func (c *UserClient) QueryTargets(_m *User) *TargetQuery {
	query := (&TargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TargetsTable, user.TargetsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySessions queries the sessions edge of a User.
func (c *UserClient) QuerySessions(_m *User) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.SessionsTable, user.SessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvites queries the invites edge of a User.
func (c *UserClient) QueryInvites(_m *User) *InviteQuery {
	query := (&InviteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(invite.Table, invite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.InvitesTable, user.InvitesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CSPScan, DataMigration, IP, ImporterConfig, Invite, Job, NotifierConfig, Port,
		PortScan, SSLScan, Session, Tag, Target, User []ent.Hook
	}
	inters struct {
		CSPScan, DataMigration, IP, ImporterConfig, Invite, Job, NotifierConfig, Port,
		PortScan, SSLScan, Session, Tag, Target, User []ent.Interceptor
	}
)
