// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"perimeter/ent/cspscan"
	"perimeter/ent/predicate"
	"perimeter/ent/target"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CSPScanQuery is the builder for querying CSPScan entities.
type CSPScanQuery struct {
	config
	ctx        *QueryContext
	order      []cspscan.OrderOption
	inters     []Interceptor
	predicates []predicate.CSPScan
	withTarget *TargetQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CSPScanQuery builder.
func (_q *CSPScanQuery) Where(ps ...predicate.CSPScan) *CSPScanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CSPScanQuery) Limit(limit int) *CSPScanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CSPScanQuery) Offset(offset int) *CSPScanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CSPScanQuery) Unique(unique bool) *CSPScanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CSPScanQuery) Order(o ...cspscan.OrderOption) *CSPScanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTarget chains the current query on the "target" edge.
func (_q *CSPScanQuery) QueryTarget() *TargetQuery {
	query := (&TargetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cspscan.Table, cspscan.FieldID, selector),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cspscan.TargetTable, cspscan.TargetColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CSPScan entity from the query.
// Returns a *NotFoundError when no CSPScan was found.
func (_q *CSPScanQuery) First(ctx context.Context) (*CSPScan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cspscan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CSPScanQuery) FirstX(ctx context.Context) *CSPScan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CSPScan ID from the query.
// Returns a *NotFoundError when no CSPScan ID was found.
func (_q *CSPScanQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cspscan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CSPScanQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CSPScan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CSPScan entity is found.
// Returns a *NotFoundError when no CSPScan entities are found.
func (_q *CSPScanQuery) Only(ctx context.Context) (*CSPScan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cspscan.Label}
	default:
		return nil, &NotSingularError{cspscan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CSPScanQuery) OnlyX(ctx context.Context) *CSPScan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CSPScan ID in the query.
// Returns a *NotSingularError when more than one CSPScan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CSPScanQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cspscan.Label}
	default:
		err = &NotSingularError{cspscan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CSPScanQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CSPScans.
func (_q *CSPScanQuery) All(ctx context.Context) ([]*CSPScan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CSPScan, *CSPScanQuery]()
	return withInterceptors[[]*CSPScan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CSPScanQuery) AllX(ctx context.Context) []*CSPScan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CSPScan IDs.
func (_q *CSPScanQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(cspscan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CSPScanQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CSPScanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CSPScanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CSPScanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CSPScanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CSPScanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CSPScanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CSPScanQuery) Clone() *CSPScanQuery {
	if _q == nil {
		return nil
	}
	return &CSPScanQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]cspscan.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.CSPScan{}, _q.predicates...),
		withTarget: _q.withTarget.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTarget tells the query-builder to eager-load the nodes that are connected to
// the "target" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CSPScanQuery) WithTarget(opts ...func(*TargetQuery)) *CSPScanQuery {
	query := (&TargetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTarget = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ScannedAt time.Time `json:"scanned_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CSPScan.Query().
//		GroupBy(cspscan.FieldScannedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CSPScanQuery) GroupBy(field string, fields ...string) *CSPScanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CSPScanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = cspscan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ScannedAt time.Time `json:"scanned_at,omitempty"`
//	}
//
//	client.CSPScan.Query().
//		Select(cspscan.FieldScannedAt).
//		Scan(ctx, &v)
func (_q *CSPScanQuery) Select(fields ...string) *CSPScanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CSPScanSelect{CSPScanQuery: _q}
	sbuild.label = cspscan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CSPScanSelect configured with the given aggregations.
func (_q *CSPScanQuery) Aggregate(fns ...AggregateFunc) *CSPScanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CSPScanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !cspscan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CSPScanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CSPScan, error) {
	var (
		nodes       = []*CSPScan{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withTarget != nil,
		}
	)
	if _q.withTarget != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, cspscan.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CSPScan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CSPScan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTarget; query != nil {
		if err := _q.loadTarget(ctx, query, nodes, nil,
			func(n *CSPScan, e *Target) { n.Edges.Target = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CSPScanQuery) loadTarget(ctx context.Context, query *TargetQuery, nodes []*CSPScan, init func(*CSPScan), assign func(*CSPScan, *Target)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CSPScan)
	for i := range nodes {
		if nodes[i].target_csp_scans == nil {
			continue
		}
		fk := *nodes[i].target_csp_scans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(target.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "target_csp_scans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CSPScanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CSPScanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cspscan.Table, cspscan.Columns, sqlgraph.NewFieldSpec(cspscan.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cspscan.FieldID)
		for i := range fields {
			if fields[i] != cspscan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CSPScanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(cspscan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = cspscan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CSPScanGroupBy is the group-by builder for CSPScan entities.
type CSPScanGroupBy struct {
	selector
	build *CSPScanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CSPScanGroupBy) Aggregate(fns ...AggregateFunc) *CSPScanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CSPScanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CSPScanQuery, *CSPScanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CSPScanGroupBy) sqlScan(ctx context.Context, root *CSPScanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CSPScanSelect is the builder for selecting fields of CSPScan entities.
type CSPScanSelect struct {
	*CSPScanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CSPScanSelect) Aggregate(fns ...AggregateFunc) *CSPScanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CSPScanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CSPScanQuery, *CSPScanSelect](ctx, _s.CSPScanQuery, _s, _s.inters, v)
}

func (_s *CSPScanSelect) sqlScan(ctx context.Context, root *CSPScanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
