// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"perimeter/ent/importerconfig"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ImporterConfig is the model entity for the ImporterConfig schema.
type ImporterConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider importerconfig.Provider `json:"provider,omitempty"`
	// Credentials holds the value of the "credentials" field.
	Credentials []byte `json:"credentials,omitempty"`
	// SyncIntervalSeconds holds the value of the "sync_interval_seconds" field.
	SyncIntervalSeconds int64 `json:"sync_interval_seconds,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImporterConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case importerconfig.FieldCredentials:
			values[i] = new([]byte)
		case importerconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case importerconfig.FieldID, importerconfig.FieldSyncIntervalSeconds:
			values[i] = new(sql.NullInt64)
		case importerconfig.FieldProvider:
			values[i] = new(sql.NullString)
		case importerconfig.FieldCreateTime, importerconfig.FieldUpdateTime, importerconfig.FieldLastSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImporterConfig fields.
func (_m *ImporterConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case importerconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case importerconfig.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case importerconfig.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case importerconfig.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = importerconfig.Provider(value.String)
			}
		case importerconfig.FieldCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value != nil {
				_m.Credentials = *value
			}
		case importerconfig.FieldSyncIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_interval_seconds", values[i])
			} else if value.Valid {
				_m.SyncIntervalSeconds = value.Int64
			}
		case importerconfig.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = new(time.Time)
				*_m.LastSyncAt = value.Time
			}
		case importerconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImporterConfig.
// This includes values selected through modifiers, order, etc.
func (_m *ImporterConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImporterConfig.
// Note that you need to call ImporterConfig.Unwrap() before calling this method if this ImporterConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImporterConfig) Update() *ImporterConfigUpdateOne {
	return NewImporterConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImporterConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImporterConfig) Unwrap() *ImporterConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImporterConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImporterConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ImporterConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("credentials=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credentials))
	builder.WriteString(", ")
	builder.WriteString("sync_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncIntervalSeconds))
	builder.WriteString(", ")
	if v := _m.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// ImporterConfigs is a parsable slice of ImporterConfig.
type ImporterConfigs []*ImporterConfig
