// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/importerconfig"
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImporterConfigUpdate is the builder for updating ImporterConfig entities.
type ImporterConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ImporterConfigMutation
}

// Where appends a list predicates to the ImporterConfigUpdate builder.
func (_u *ImporterConfigUpdate) Where(ps ...predicate.ImporterConfig) *ImporterConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ImporterConfigUpdate) SetUpdateTime(v time.Time) *ImporterConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImporterConfigUpdate) SetProvider(v importerconfig.Provider) *ImporterConfigUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImporterConfigUpdate) SetNillableProvider(v *importerconfig.Provider) *ImporterConfigUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ImporterConfigUpdate) SetCredentials(v []byte) *ImporterConfigUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetSyncIntervalSeconds sets the "sync_interval_seconds" field.
func (_u *ImporterConfigUpdate) SetSyncIntervalSeconds(v int64) *ImporterConfigUpdate {
	_u.mutation.ResetSyncIntervalSeconds()
	_u.mutation.SetSyncIntervalSeconds(v)
	return _u
}

// SetNillableSyncIntervalSeconds sets the "sync_interval_seconds" field if the given value is not nil.
func (_u *ImporterConfigUpdate) SetNillableSyncIntervalSeconds(v *int64) *ImporterConfigUpdate {
	if v != nil {
		_u.SetSyncIntervalSeconds(*v)
	}
	return _u
}

// AddSyncIntervalSeconds adds value to the "sync_interval_seconds" field.
func (_u *ImporterConfigUpdate) AddSyncIntervalSeconds(v int64) *ImporterConfigUpdate {
	_u.mutation.AddSyncIntervalSeconds(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *ImporterConfigUpdate) SetLastSyncAt(v time.Time) *ImporterConfigUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *ImporterConfigUpdate) SetNillableLastSyncAt(v *time.Time) *ImporterConfigUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *ImporterConfigUpdate) ClearLastSyncAt() *ImporterConfigUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImporterConfigUpdate) SetEnabled(v bool) *ImporterConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImporterConfigUpdate) SetNillableEnabled(v *bool) *ImporterConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ImporterConfigMutation object of the builder.
func (_u *ImporterConfigUpdate) Mutation() *ImporterConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImporterConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImporterConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImporterConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImporterConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImporterConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := importerconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImporterConfigUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := importerconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImporterConfig.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *ImporterConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(importerconfig.Table, importerconfig.Columns, sqlgraph.NewFieldSpec(importerconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(importerconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(importerconfig.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(importerconfig.FieldCredentials, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SyncIntervalSeconds(); ok {
		_spec.SetField(importerconfig.FieldSyncIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalSeconds(); ok {
		_spec.AddField(importerconfig.FieldSyncIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(importerconfig.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(importerconfig.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(importerconfig.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{importerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImporterConfigUpdateOne is the builder for updating a single ImporterConfig entity.
type ImporterConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImporterConfigMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ImporterConfigUpdateOne) SetUpdateTime(v time.Time) *ImporterConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImporterConfigUpdateOne) SetProvider(v importerconfig.Provider) *ImporterConfigUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImporterConfigUpdateOne) SetNillableProvider(v *importerconfig.Provider) *ImporterConfigUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ImporterConfigUpdateOne) SetCredentials(v []byte) *ImporterConfigUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetSyncIntervalSeconds sets the "sync_interval_seconds" field.
func (_u *ImporterConfigUpdateOne) SetSyncIntervalSeconds(v int64) *ImporterConfigUpdateOne {
	_u.mutation.ResetSyncIntervalSeconds()
	_u.mutation.SetSyncIntervalSeconds(v)
	return _u
}

// SetNillableSyncIntervalSeconds sets the "sync_interval_seconds" field if the given value is not nil.
func (_u *ImporterConfigUpdateOne) SetNillableSyncIntervalSeconds(v *int64) *ImporterConfigUpdateOne {
	if v != nil {
		_u.SetSyncIntervalSeconds(*v)
	}
	return _u
}

// AddSyncIntervalSeconds adds value to the "sync_interval_seconds" field.
func (_u *ImporterConfigUpdateOne) AddSyncIntervalSeconds(v int64) *ImporterConfigUpdateOne {
	_u.mutation.AddSyncIntervalSeconds(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *ImporterConfigUpdateOne) SetLastSyncAt(v time.Time) *ImporterConfigUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *ImporterConfigUpdateOne) SetNillableLastSyncAt(v *time.Time) *ImporterConfigUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *ImporterConfigUpdateOne) ClearLastSyncAt() *ImporterConfigUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImporterConfigUpdateOne) SetEnabled(v bool) *ImporterConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImporterConfigUpdateOne) SetNillableEnabled(v *bool) *ImporterConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ImporterConfigMutation object of the builder.
func (_u *ImporterConfigUpdateOne) Mutation() *ImporterConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImporterConfigUpdate builder.
func (_u *ImporterConfigUpdateOne) Where(ps ...predicate.ImporterConfig) *ImporterConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImporterConfigUpdateOne) Select(field string, fields ...string) *ImporterConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImporterConfig entity.
func (_u *ImporterConfigUpdateOne) Save(ctx context.Context) (*ImporterConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImporterConfigUpdateOne) SaveX(ctx context.Context) *ImporterConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImporterConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImporterConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImporterConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := importerconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImporterConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := importerconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImporterConfig.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *ImporterConfigUpdateOne) sqlSave(ctx context.Context) (_node *ImporterConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(importerconfig.Table, importerconfig.Columns, sqlgraph.NewFieldSpec(importerconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImporterConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, importerconfig.FieldID)
		for _, f := range fields {
			if !importerconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != importerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(importerconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(importerconfig.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(importerconfig.FieldCredentials, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SyncIntervalSeconds(); ok {
		_spec.SetField(importerconfig.FieldSyncIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalSeconds(); ok {
		_spec.AddField(importerconfig.FieldSyncIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(importerconfig.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(importerconfig.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(importerconfig.FieldEnabled, field.TypeBool, value)
	}
	_node = &ImporterConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{importerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
