// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/invite"
	"perimeter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InviteCreate is the builder for creating a Invite entity.
type InviteCreate struct {
	config
	mutation *InviteMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *InviteCreate) SetCreateTime(v time.Time) *InviteCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *InviteCreate) SetNillableCreateTime(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *InviteCreate) SetUpdateTime(v time.Time) *InviteCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *InviteCreate) SetNillableUpdateTime(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *InviteCreate) SetEmail(v string) *InviteCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *InviteCreate) SetTokenHash(v string) *InviteCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *InviteCreate) SetRole(v invite.Role) *InviteCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *InviteCreate) SetNillableRole(v *invite.Role) *InviteCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InviteCreate) SetExpiresAt(v time.Time) *InviteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *InviteCreate) SetAcceptedAt(v time.Time) *InviteCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *InviteCreate) SetNillableAcceptedAt(v *time.Time) *InviteCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetInvitedByID sets the "invited_by" edge to the User entity by ID.
func (_c *InviteCreate) SetInvitedByID(id int) *InviteCreate {
	_c.mutation.SetInvitedByID(id)
	return _c
}

// SetInvitedBy sets the "invited_by" edge to the User entity.
func (_c *InviteCreate) SetInvitedBy(v *User) *InviteCreate {
	return _c.SetInvitedByID(v.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (_c *InviteCreate) Mutation() *InviteMutation {
	return _c.mutation
}

// Save creates the Invite in the database.
func (_c *InviteCreate) Save(ctx context.Context) (*Invite, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteCreate) SaveX(ctx context.Context) *Invite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := invite.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := invite.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := invite.DefaultRole
		_c.mutation.SetRole(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Invite.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Invite.update_time"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Invite.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "Invite.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := invite.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Invite.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Invite.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := invite.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Invite.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Invite.expires_at"`)}
	}
	if len(_c.mutation.InvitedByIDs()) == 0 {
		return &ValidationError{Name: "invited_by", err: errors.New(`ent: missing required edge "Invite.invited_by"`)}
	}
	return nil
}

func (_c *InviteCreate) sqlSave(ctx context.Context) (*Invite, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteCreate) createSpec() (*Invite, *sqlgraph.CreateSpec) {
	var (
		_node = &Invite{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invite.Table, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(invite.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(invite.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(invite.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(invite.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(invite.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if nodes := _c.mutation.InvitedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InvitedByTable,
			Columns: []string{invite.InvitedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_invites = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InviteCreateBulk is the builder for creating many Invite entities in bulk.
type InviteCreateBulk struct {
	config
	err      error
	builders []*InviteCreate
}

// Save creates the Invite entities in the database.
func (_c *InviteCreateBulk) Save(ctx context.Context) ([]*Invite, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invite, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteCreateBulk) SaveX(ctx context.Context) []*Invite {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
