// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"perimeter/ent/ip"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// IP is the model entity for the IP schema.
type IP struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IPQuery when eager-loading is set.
	Edges        IPEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IPEdges holds the relations/edges for other nodes in the graph.
type IPEdges struct {
	// Targets holds the value of the targets edge.
	Targets []*Target `json:"targets,omitempty"`
	// Scans holds the value of the scans edge.
	Scans []*PortScan `json:"scans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TargetsOrErr returns the Targets value or an error if the edge
// was not loaded in eager-loading.
func (e IPEdges) TargetsOrErr() ([]*Target, error) {
	if e.loadedTypes[0] {
		return e.Targets, nil
	}
	return nil, &NotLoadedError{edge: "targets"}
}

// ScansOrErr returns the Scans value or an error if the edge
// was not loaded in eager-loading.
func (e IPEdges) ScansOrErr() ([]*PortScan, error) {
	if e.loadedTypes[1] {
		return e.Scans, nil
	}
	return nil, &NotLoadedError{edge: "scans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IP) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ip.FieldID:
			values[i] = new(sql.NullInt64)
		case ip.FieldAddress:
			values[i] = new(sql.NullString)
		case ip.FieldCreateTime, ip.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IP fields.
func (_m *IP) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ip.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ip.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case ip.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case ip.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IP.
// This includes values selected through modifiers, order, etc.
func (_m *IP) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTargets queries the "targets" edge of the IP entity.
func (_m *IP) QueryTargets() *TargetQuery {
	return NewIPClient(_m.config).QueryTargets(_m)
}

// QueryScans queries the "scans" edge of the IP entity.
func (_m *IP) QueryScans() *PortScanQuery {
	return NewIPClient(_m.config).QueryScans(_m)
}

// Update returns a builder for updating this IP.
// Note that you need to call IP.Unwrap() before calling this method if this IP
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IP) Update() *IPUpdateOne {
	return NewIPClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IP entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IP) Unwrap() *IP {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IP is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IP) String() string {
	var builder strings.Builder
	builder.WriteString("IP(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteByte(')')
	return builder.String()
}

// IPs is a parsable slice of IP.
type IPs []*IP
