// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/notifierconfig"
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotifierConfigUpdate is the builder for updating NotifierConfig entities.
type NotifierConfigUpdate struct {
	config
	hooks    []Hook
	mutation *NotifierConfigMutation
}

// Where appends a list predicates to the NotifierConfigUpdate builder.
func (_u *NotifierConfigUpdate) Where(ps ...predicate.NotifierConfig) *NotifierConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *NotifierConfigUpdate) SetUpdateTime(v time.Time) *NotifierConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *NotifierConfigUpdate) SetProvider(v notifierconfig.Provider) *NotifierConfigUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *NotifierConfigUpdate) SetNillableProvider(v *notifierconfig.Provider) *NotifierConfigUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotifierConfigUpdate) SetConfig(v []byte) *NotifierConfigUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifierConfigUpdate) SetEnabled(v bool) *NotifierConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifierConfigUpdate) SetNillableEnabled(v *bool) *NotifierConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the NotifierConfigMutation object of the builder.
func (_u *NotifierConfigUpdate) Mutation() *NotifierConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifierConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifierConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifierConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifierConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifierConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := notifierconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifierConfigUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := notifierconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "NotifierConfig.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifierConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifierconfig.Table, notifierconfig.Columns, sqlgraph.NewFieldSpec(notifierconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(notifierconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(notifierconfig.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notifierconfig.FieldConfig, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifierconfig.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifierconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifierConfigUpdateOne is the builder for updating a single NotifierConfig entity.
type NotifierConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotifierConfigMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *NotifierConfigUpdateOne) SetUpdateTime(v time.Time) *NotifierConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *NotifierConfigUpdateOne) SetProvider(v notifierconfig.Provider) *NotifierConfigUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *NotifierConfigUpdateOne) SetNillableProvider(v *notifierconfig.Provider) *NotifierConfigUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotifierConfigUpdateOne) SetConfig(v []byte) *NotifierConfigUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifierConfigUpdateOne) SetEnabled(v bool) *NotifierConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifierConfigUpdateOne) SetNillableEnabled(v *bool) *NotifierConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the NotifierConfigMutation object of the builder.
func (_u *NotifierConfigUpdateOne) Mutation() *NotifierConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotifierConfigUpdate builder.
func (_u *NotifierConfigUpdateOne) Where(ps ...predicate.NotifierConfig) *NotifierConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifierConfigUpdateOne) Select(field string, fields ...string) *NotifierConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifierConfig entity.
func (_u *NotifierConfigUpdateOne) Save(ctx context.Context) (*NotifierConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifierConfigUpdateOne) SaveX(ctx context.Context) *NotifierConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifierConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifierConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifierConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := notifierconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifierConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := notifierconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "NotifierConfig.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifierConfigUpdateOne) sqlSave(ctx context.Context) (_node *NotifierConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifierconfig.Table, notifierconfig.Columns, sqlgraph.NewFieldSpec(notifierconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotifierConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifierconfig.FieldID)
		for _, f := range fields {
			if !notifierconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notifierconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(notifierconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(notifierconfig.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notifierconfig.FieldConfig, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifierconfig.FieldEnabled, field.TypeBool, value)
	}
	_node = &NotifierConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifierconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
