// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/port"
	"perimeter/ent/portscan"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortCreate is the builder for creating a Port entity.
type PortCreate struct {
	config
	mutation *PortMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (_c *PortCreate) SetNumber(v int) *PortCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetScanID sets the "scan" edge to the PortScan entity by ID.
func (_c *PortCreate) SetScanID(id int) *PortCreate {
	_c.mutation.SetScanID(id)
	return _c
}

// SetScan sets the "scan" edge to the PortScan entity.
func (_c *PortCreate) SetScan(v *PortScan) *PortCreate {
	return _c.SetScanID(v.ID)
}

// Mutation returns the PortMutation object of the builder.
func (_c *PortCreate) Mutation() *PortMutation {
	return _c.mutation
}

// Save creates the Port in the database.
func (_c *PortCreate) Save(ctx context.Context) (*Port, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PortCreate) SaveX(ctx context.Context) *Port {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PortCreate) check() error {
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Port.number"`)}
	}
	if len(_c.mutation.ScanIDs()) == 0 {
		return &ValidationError{Name: "scan", err: errors.New(`ent: missing required edge "Port.scan"`)}
	}
	return nil
}

func (_c *PortCreate) sqlSave(ctx context.Context) (*Port, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PortCreate) createSpec() (*Port, *sqlgraph.CreateSpec) {
	var (
		_node = &Port{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(port.Table, sqlgraph.NewFieldSpec(port.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(port.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if nodes := _c.mutation.ScanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   port.ScanTable,
			Columns: []string{port.ScanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.port_scan_ports = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PortCreateBulk is the builder for creating many Port entities in bulk.
type PortCreateBulk struct {
	config
	err      error
	builders []*PortCreate
}

// Save creates the Port entities in the database.
func (_c *PortCreateBulk) Save(ctx context.Context) ([]*Port, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Port, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PortCreateBulk) SaveX(ctx context.Context) []*Port {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
