// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"perimeter/ent/port"
	"perimeter/ent/portscan"
	"perimeter/ent/predicate"
	"perimeter/ent/target"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortScanQuery is the builder for querying PortScan entities.
type PortScanQuery struct {
	config
	ctx        *QueryContext
	order      []portscan.OrderOption
	inters     []Interceptor
	predicates []predicate.PortScan
	withTarget *TargetQuery
	withPorts  *PortQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PortScanQuery builder.
func (_q *PortScanQuery) Where(ps ...predicate.PortScan) *PortScanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PortScanQuery) Limit(limit int) *PortScanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PortScanQuery) Offset(offset int) *PortScanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PortScanQuery) Unique(unique bool) *PortScanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PortScanQuery) Order(o ...portscan.OrderOption) *PortScanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTarget chains the current query on the "target" edge.
func (_q *PortScanQuery) QueryTarget() *TargetQuery {
	query := (&TargetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portscan.Table, portscan.FieldID, selector),
			sqlgraph.To(target.Table, target.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, portscan.TargetTable, portscan.TargetColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPorts chains the current query on the "ports" edge.
func (_q *PortScanQuery) QueryPorts() *PortQuery {
	query := (&PortClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portscan.Table, portscan.FieldID, selector),
			sqlgraph.To(port.Table, port.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, portscan.PortsTable, portscan.PortsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PortScan entity from the query.
// Returns a *NotFoundError when no PortScan was found.
func (_q *PortScanQuery) First(ctx context.Context) (*PortScan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{portscan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PortScanQuery) FirstX(ctx context.Context) *PortScan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PortScan ID from the query.
// Returns a *NotFoundError when no PortScan ID was found.
func (_q *PortScanQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{portscan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PortScanQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PortScan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PortScan entity is found.
// Returns a *NotFoundError when no PortScan entities are found.
func (_q *PortScanQuery) Only(ctx context.Context) (*PortScan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{portscan.Label}
	default:
		return nil, &NotSingularError{portscan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PortScanQuery) OnlyX(ctx context.Context) *PortScan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PortScan ID in the query.
// Returns a *NotSingularError when more than one PortScan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PortScanQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{portscan.Label}
	default:
		err = &NotSingularError{portscan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PortScanQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PortScans.
func (_q *PortScanQuery) All(ctx context.Context) ([]*PortScan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PortScan, *PortScanQuery]()
	return withInterceptors[[]*PortScan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PortScanQuery) AllX(ctx context.Context) []*PortScan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PortScan IDs.
func (_q *PortScanQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(portscan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PortScanQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PortScanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PortScanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PortScanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PortScanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PortScanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PortScanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PortScanQuery) Clone() *PortScanQuery {
	if _q == nil {
		return nil
	}
	return &PortScanQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]portscan.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PortScan{}, _q.predicates...),
		withTarget: _q.withTarget.Clone(),
		withPorts:  _q.withPorts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTarget tells the query-builder to eager-load the nodes that are connected to
// the "target" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PortScanQuery) WithTarget(opts ...func(*TargetQuery)) *PortScanQuery {
	query := (&TargetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTarget = query
	return _q
}

// WithPorts tells the query-builder to eager-load the nodes that are connected to
// the "ports" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PortScanQuery) WithPorts(opts ...func(*PortQuery)) *PortScanQuery {
	query := (&PortClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPorts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ScannedAt time.Time `json:"scanned_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PortScan.Query().
//		GroupBy(portscan.FieldScannedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PortScanQuery) GroupBy(field string, fields ...string) *PortScanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PortScanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = portscan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ScannedAt time.Time `json:"scanned_at,omitempty"`
//	}
//
//	client.PortScan.Query().
//		Select(portscan.FieldScannedAt).
//		Scan(ctx, &v)
func (_q *PortScanQuery) Select(fields ...string) *PortScanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PortScanSelect{PortScanQuery: _q}
	sbuild.label = portscan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PortScanSelect configured with the given aggregations.
func (_q *PortScanQuery) Aggregate(fns ...AggregateFunc) *PortScanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PortScanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !portscan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PortScanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PortScan, error) {
	var (
		nodes       = []*PortScan{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTarget != nil,
			_q.withPorts != nil,
		}
	)
	if _q.withTarget != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, portscan.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PortScan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PortScan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTarget; query != nil {
		if err := _q.loadTarget(ctx, query, nodes, nil,
			func(n *PortScan, e *Target) { n.Edges.Target = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPorts; query != nil {
		if err := _q.loadPorts(ctx, query, nodes,
			func(n *PortScan) { n.Edges.Ports = []*Port{} },
			func(n *PortScan, e *Port) { n.Edges.Ports = append(n.Edges.Ports, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PortScanQuery) loadTarget(ctx context.Context, query *TargetQuery, nodes []*PortScan, init func(*PortScan), assign func(*PortScan, *Target)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PortScan)
	for i := range nodes {
		if nodes[i].target_scans == nil {
			continue
		}
		fk := *nodes[i].target_scans
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(target.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "target_scans" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PortScanQuery) loadPorts(ctx context.Context, query *PortQuery, nodes []*PortScan, init func(*PortScan), assign func(*PortScan, *Port)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PortScan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Port(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(portscan.PortsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.port_scan_ports
		if fk == nil {
			return fmt.Errorf(`foreign-key "port_scan_ports" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "port_scan_ports" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PortScanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PortScanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(portscan.Table, portscan.Columns, sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portscan.FieldID)
		for i := range fields {
			if fields[i] != portscan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PortScanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(portscan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = portscan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PortScanGroupBy is the group-by builder for PortScan entities.
type PortScanGroupBy struct {
	selector
	build *PortScanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PortScanGroupBy) Aggregate(fns ...AggregateFunc) *PortScanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PortScanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortScanQuery, *PortScanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PortScanGroupBy) sqlScan(ctx context.Context, root *PortScanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PortScanSelect is the builder for selecting fields of PortScan entities.
type PortScanSelect struct {
	*PortScanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PortScanSelect) Aggregate(fns ...AggregateFunc) *PortScanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PortScanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortScanQuery, *PortScanSelect](ctx, _s.PortScanQuery, _s, _s.inters, v)
}

func (_s *PortScanSelect) sqlScan(ctx context.Context, root *PortScanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
