// Code generated by ent, DO NOT EDIT.

package ent

import (
	"perimeter/ent/portscan"
	"perimeter/ent/schema"
	"perimeter/ent/target"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	portscanFields := schema.PortScan{}.Fields()
	_ = portscanFields
	// portscanDescScannedAt is the schema descriptor for scanned_at field.
	portscanDescScannedAt := portscanFields[0].Descriptor()
	// portscan.DefaultScannedAt holds the default value on creation for the scanned_at field.
	portscan.DefaultScannedAt = portscanDescScannedAt.Default.(func() time.Time)
	targetMixin := schema.Target{}.Mixin()
	targetMixinFields0 := targetMixin[0].Fields()
	_ = targetMixinFields0
	targetFields := schema.Target{}.Fields()
	_ = targetFields
	// targetDescCreateTime is the schema descriptor for create_time field.
	targetDescCreateTime := targetMixinFields0[0].Descriptor()
	// target.DefaultCreateTime holds the default value on creation for the create_time field.
	target.DefaultCreateTime = targetDescCreateTime.Default.(func() time.Time)
	// targetDescUpdateTime is the schema descriptor for update_time field.
	targetDescUpdateTime := targetMixinFields0[1].Descriptor()
	// target.DefaultUpdateTime holds the default value on creation for the update_time field.
	target.DefaultUpdateTime = targetDescUpdateTime.Default.(func() time.Time)
	// target.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	target.UpdateDefaultUpdateTime = targetDescUpdateTime.UpdateDefault.(func() time.Time)
	// targetDescInput is the schema descriptor for input field.
	targetDescInput := targetFields[0].Descriptor()
	// target.InputValidator is a validator for the "input" field. It is called by the builders before save.
	target.InputValidator = targetDescInput.Validators[0].(func(string) error)
}
