// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/predicate"
	"perimeter/ent/sslscan"
	"perimeter/ent/target"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SSLScanUpdate is the builder for updating SSLScan entities.
type SSLScanUpdate struct {
	config
	hooks    []Hook
	mutation *SSLScanMutation
}

// Where appends a list predicates to the SSLScanUpdate builder.
func (_u *SSLScanUpdate) Where(ps ...predicate.SSLScan) *SSLScanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScannedAt sets the "scanned_at" field.
func (_u *SSLScanUpdate) SetScannedAt(v time.Time) *SSLScanUpdate {
	_u.mutation.SetScannedAt(v)
	return _u
}

// SetNillableScannedAt sets the "scanned_at" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableScannedAt(v *time.Time) *SSLScanUpdate {
	if v != nil {
		_u.SetScannedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *SSLScanUpdate) SetLastSeenAt(v time.Time) *SSLScanUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableLastSeenAt(v *time.Time) *SSLScanUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *SSLScanUpdate) ClearLastSeenAt() *SSLScanUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetCheckCount sets the "check_count" field.
func (_u *SSLScanUpdate) SetCheckCount(v int) *SSLScanUpdate {
	_u.mutation.ResetCheckCount()
	_u.mutation.SetCheckCount(v)
	return _u
}

// SetNillableCheckCount sets the "check_count" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableCheckCount(v *int) *SSLScanUpdate {
	if v != nil {
		_u.SetCheckCount(*v)
	}
	return _u
}

// AddCheckCount adds value to the "check_count" field.
func (_u *SSLScanUpdate) AddCheckCount(v int) *SSLScanUpdate {
	_u.mutation.AddCheckCount(v)
	return _u
}

// SetGrade sets the "grade" field.
func (_u *SSLScanUpdate) SetGrade(v string) *SSLScanUpdate {
	_u.mutation.SetGrade(v)
	return _u
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableGrade(v *string) *SSLScanUpdate {
	if v != nil {
		_u.SetGrade(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SSLScanUpdate) SetStatus(v string) *SSLScanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableStatus(v *string) *SSLScanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCertIssuer sets the "cert_issuer" field.
func (_u *SSLScanUpdate) SetCertIssuer(v string) *SSLScanUpdate {
	_u.mutation.SetCertIssuer(v)
	return _u
}

// SetNillableCertIssuer sets the "cert_issuer" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableCertIssuer(v *string) *SSLScanUpdate {
	if v != nil {
		_u.SetCertIssuer(*v)
	}
	return _u
}

// ClearCertIssuer clears the value of the "cert_issuer" field.
func (_u *SSLScanUpdate) ClearCertIssuer() *SSLScanUpdate {
	_u.mutation.ClearCertIssuer()
	return _u
}

// SetCertSubject sets the "cert_subject" field.
func (_u *SSLScanUpdate) SetCertSubject(v string) *SSLScanUpdate {
	_u.mutation.SetCertSubject(v)
	return _u
}

// SetNillableCertSubject sets the "cert_subject" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableCertSubject(v *string) *SSLScanUpdate {
	if v != nil {
		_u.SetCertSubject(*v)
	}
	return _u
}

// ClearCertSubject clears the value of the "cert_subject" field.
func (_u *SSLScanUpdate) ClearCertSubject() *SSLScanUpdate {
	_u.mutation.ClearCertSubject()
	return _u
}

// SetCertExpiry sets the "cert_expiry" field.
func (_u *SSLScanUpdate) SetCertExpiry(v time.Time) *SSLScanUpdate {
	_u.mutation.SetCertExpiry(v)
	return _u
}

// SetNillableCertExpiry sets the "cert_expiry" field if the given value is not nil.
func (_u *SSLScanUpdate) SetNillableCertExpiry(v *time.Time) *SSLScanUpdate {
	if v != nil {
		_u.SetCertExpiry(*v)
	}
	return _u
}

// ClearCertExpiry clears the value of the "cert_expiry" field.
func (_u *SSLScanUpdate) ClearCertExpiry() *SSLScanUpdate {
	_u.mutation.ClearCertExpiry()
	return _u
}

// SetProtocols sets the "protocols" field.
func (_u *SSLScanUpdate) SetProtocols(v []string) *SSLScanUpdate {
	_u.mutation.SetProtocols(v)
	return _u
}

// AppendProtocols appends value to the "protocols" field.
func (_u *SSLScanUpdate) AppendProtocols(v []string) *SSLScanUpdate {
	_u.mutation.AppendProtocols(v)
	return _u
}

// ClearProtocols clears the value of the "protocols" field.
func (_u *SSLScanUpdate) ClearProtocols() *SSLScanUpdate {
	_u.mutation.ClearProtocols()
	return _u
}

// SetVulnerabilities sets the "vulnerabilities" field.
func (_u *SSLScanUpdate) SetVulnerabilities(v []string) *SSLScanUpdate {
	_u.mutation.SetVulnerabilities(v)
	return _u
}

// AppendVulnerabilities appends value to the "vulnerabilities" field.
func (_u *SSLScanUpdate) AppendVulnerabilities(v []string) *SSLScanUpdate {
	_u.mutation.AppendVulnerabilities(v)
	return _u
}

// ClearVulnerabilities clears the value of the "vulnerabilities" field.
func (_u *SSLScanUpdate) ClearVulnerabilities() *SSLScanUpdate {
	_u.mutation.ClearVulnerabilities()
	return _u
}

// SetTargetID sets the "target" edge to the Target entity by ID.
func (_u *SSLScanUpdate) SetTargetID(id int) *SSLScanUpdate {
	_u.mutation.SetTargetID(id)
	return _u
}

// SetTarget sets the "target" edge to the Target entity.
func (_u *SSLScanUpdate) SetTarget(v *Target) *SSLScanUpdate {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the SSLScanMutation object of the builder.
func (_u *SSLScanUpdate) Mutation() *SSLScanMutation {
	return _u.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (_u *SSLScanUpdate) ClearTarget() *SSLScanUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SSLScanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SSLScanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SSLScanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SSLScanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SSLScanUpdate) check() error {
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SSLScan.target"`)
	}
	return nil
}

func (_u *SSLScanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sslscan.Table, sslscan.Columns, sqlgraph.NewFieldSpec(sslscan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScannedAt(); ok {
		_spec.SetField(sslscan.FieldScannedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(sslscan.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(sslscan.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CheckCount(); ok {
		_spec.SetField(sslscan.FieldCheckCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCheckCount(); ok {
		_spec.AddField(sslscan.FieldCheckCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Grade(); ok {
		_spec.SetField(sslscan.FieldGrade, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sslscan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertIssuer(); ok {
		_spec.SetField(sslscan.FieldCertIssuer, field.TypeString, value)
	}
	if _u.mutation.CertIssuerCleared() {
		_spec.ClearField(sslscan.FieldCertIssuer, field.TypeString)
	}
	if value, ok := _u.mutation.CertSubject(); ok {
		_spec.SetField(sslscan.FieldCertSubject, field.TypeString, value)
	}
	if _u.mutation.CertSubjectCleared() {
		_spec.ClearField(sslscan.FieldCertSubject, field.TypeString)
	}
	if value, ok := _u.mutation.CertExpiry(); ok {
		_spec.SetField(sslscan.FieldCertExpiry, field.TypeTime, value)
	}
	if _u.mutation.CertExpiryCleared() {
		_spec.ClearField(sslscan.FieldCertExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Protocols(); ok {
		_spec.SetField(sslscan.FieldProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sslscan.FieldProtocols, value)
		})
	}
	if _u.mutation.ProtocolsCleared() {
		_spec.ClearField(sslscan.FieldProtocols, field.TypeJSON)
	}
	if value, ok := _u.mutation.Vulnerabilities(); ok {
		_spec.SetField(sslscan.FieldVulnerabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVulnerabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sslscan.FieldVulnerabilities, value)
		})
	}
	if _u.mutation.VulnerabilitiesCleared() {
		_spec.ClearField(sslscan.FieldVulnerabilities, field.TypeJSON)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sslscan.TargetTable,
			Columns: []string{sslscan.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sslscan.TargetTable,
			Columns: []string{sslscan.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sslscan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SSLScanUpdateOne is the builder for updating a single SSLScan entity.
type SSLScanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SSLScanMutation
}

// SetScannedAt sets the "scanned_at" field.
func (_u *SSLScanUpdateOne) SetScannedAt(v time.Time) *SSLScanUpdateOne {
	_u.mutation.SetScannedAt(v)
	return _u
}

// SetNillableScannedAt sets the "scanned_at" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableScannedAt(v *time.Time) *SSLScanUpdateOne {
	if v != nil {
		_u.SetScannedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *SSLScanUpdateOne) SetLastSeenAt(v time.Time) *SSLScanUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableLastSeenAt(v *time.Time) *SSLScanUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *SSLScanUpdateOne) ClearLastSeenAt() *SSLScanUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetCheckCount sets the "check_count" field.
func (_u *SSLScanUpdateOne) SetCheckCount(v int) *SSLScanUpdateOne {
	_u.mutation.ResetCheckCount()
	_u.mutation.SetCheckCount(v)
	return _u
}

// SetNillableCheckCount sets the "check_count" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableCheckCount(v *int) *SSLScanUpdateOne {
	if v != nil {
		_u.SetCheckCount(*v)
	}
	return _u
}

// AddCheckCount adds value to the "check_count" field.
func (_u *SSLScanUpdateOne) AddCheckCount(v int) *SSLScanUpdateOne {
	_u.mutation.AddCheckCount(v)
	return _u
}

// SetGrade sets the "grade" field.
func (_u *SSLScanUpdateOne) SetGrade(v string) *SSLScanUpdateOne {
	_u.mutation.SetGrade(v)
	return _u
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableGrade(v *string) *SSLScanUpdateOne {
	if v != nil {
		_u.SetGrade(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SSLScanUpdateOne) SetStatus(v string) *SSLScanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableStatus(v *string) *SSLScanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCertIssuer sets the "cert_issuer" field.
func (_u *SSLScanUpdateOne) SetCertIssuer(v string) *SSLScanUpdateOne {
	_u.mutation.SetCertIssuer(v)
	return _u
}

// SetNillableCertIssuer sets the "cert_issuer" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableCertIssuer(v *string) *SSLScanUpdateOne {
	if v != nil {
		_u.SetCertIssuer(*v)
	}
	return _u
}

// ClearCertIssuer clears the value of the "cert_issuer" field.
func (_u *SSLScanUpdateOne) ClearCertIssuer() *SSLScanUpdateOne {
	_u.mutation.ClearCertIssuer()
	return _u
}

// SetCertSubject sets the "cert_subject" field.
func (_u *SSLScanUpdateOne) SetCertSubject(v string) *SSLScanUpdateOne {
	_u.mutation.SetCertSubject(v)
	return _u
}

// SetNillableCertSubject sets the "cert_subject" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableCertSubject(v *string) *SSLScanUpdateOne {
	if v != nil {
		_u.SetCertSubject(*v)
	}
	return _u
}

// ClearCertSubject clears the value of the "cert_subject" field.
func (_u *SSLScanUpdateOne) ClearCertSubject() *SSLScanUpdateOne {
	_u.mutation.ClearCertSubject()
	return _u
}

// SetCertExpiry sets the "cert_expiry" field.
func (_u *SSLScanUpdateOne) SetCertExpiry(v time.Time) *SSLScanUpdateOne {
	_u.mutation.SetCertExpiry(v)
	return _u
}

// SetNillableCertExpiry sets the "cert_expiry" field if the given value is not nil.
func (_u *SSLScanUpdateOne) SetNillableCertExpiry(v *time.Time) *SSLScanUpdateOne {
	if v != nil {
		_u.SetCertExpiry(*v)
	}
	return _u
}

// ClearCertExpiry clears the value of the "cert_expiry" field.
func (_u *SSLScanUpdateOne) ClearCertExpiry() *SSLScanUpdateOne {
	_u.mutation.ClearCertExpiry()
	return _u
}

// SetProtocols sets the "protocols" field.
func (_u *SSLScanUpdateOne) SetProtocols(v []string) *SSLScanUpdateOne {
	_u.mutation.SetProtocols(v)
	return _u
}

// AppendProtocols appends value to the "protocols" field.
func (_u *SSLScanUpdateOne) AppendProtocols(v []string) *SSLScanUpdateOne {
	_u.mutation.AppendProtocols(v)
	return _u
}

// ClearProtocols clears the value of the "protocols" field.
func (_u *SSLScanUpdateOne) ClearProtocols() *SSLScanUpdateOne {
	_u.mutation.ClearProtocols()
	return _u
}

// SetVulnerabilities sets the "vulnerabilities" field.
func (_u *SSLScanUpdateOne) SetVulnerabilities(v []string) *SSLScanUpdateOne {
	_u.mutation.SetVulnerabilities(v)
	return _u
}

// AppendVulnerabilities appends value to the "vulnerabilities" field.
func (_u *SSLScanUpdateOne) AppendVulnerabilities(v []string) *SSLScanUpdateOne {
	_u.mutation.AppendVulnerabilities(v)
	return _u
}

// ClearVulnerabilities clears the value of the "vulnerabilities" field.
func (_u *SSLScanUpdateOne) ClearVulnerabilities() *SSLScanUpdateOne {
	_u.mutation.ClearVulnerabilities()
	return _u
}

// SetTargetID sets the "target" edge to the Target entity by ID.
func (_u *SSLScanUpdateOne) SetTargetID(id int) *SSLScanUpdateOne {
	_u.mutation.SetTargetID(id)
	return _u
}

// SetTarget sets the "target" edge to the Target entity.
func (_u *SSLScanUpdateOne) SetTarget(v *Target) *SSLScanUpdateOne {
	return _u.SetTargetID(v.ID)
}

// Mutation returns the SSLScanMutation object of the builder.
func (_u *SSLScanUpdateOne) Mutation() *SSLScanMutation {
	return _u.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (_u *SSLScanUpdateOne) ClearTarget() *SSLScanUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// Where appends a list predicates to the SSLScanUpdate builder.
func (_u *SSLScanUpdateOne) Where(ps ...predicate.SSLScan) *SSLScanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SSLScanUpdateOne) Select(field string, fields ...string) *SSLScanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SSLScan entity.
func (_u *SSLScanUpdateOne) Save(ctx context.Context) (*SSLScan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SSLScanUpdateOne) SaveX(ctx context.Context) *SSLScan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SSLScanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SSLScanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SSLScanUpdateOne) check() error {
	if _u.mutation.TargetCleared() && len(_u.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SSLScan.target"`)
	}
	return nil
}

func (_u *SSLScanUpdateOne) sqlSave(ctx context.Context) (_node *SSLScan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sslscan.Table, sslscan.Columns, sqlgraph.NewFieldSpec(sslscan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SSLScan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sslscan.FieldID)
		for _, f := range fields {
			if !sslscan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sslscan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScannedAt(); ok {
		_spec.SetField(sslscan.FieldScannedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(sslscan.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(sslscan.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CheckCount(); ok {
		_spec.SetField(sslscan.FieldCheckCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCheckCount(); ok {
		_spec.AddField(sslscan.FieldCheckCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Grade(); ok {
		_spec.SetField(sslscan.FieldGrade, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sslscan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertIssuer(); ok {
		_spec.SetField(sslscan.FieldCertIssuer, field.TypeString, value)
	}
	if _u.mutation.CertIssuerCleared() {
		_spec.ClearField(sslscan.FieldCertIssuer, field.TypeString)
	}
	if value, ok := _u.mutation.CertSubject(); ok {
		_spec.SetField(sslscan.FieldCertSubject, field.TypeString, value)
	}
	if _u.mutation.CertSubjectCleared() {
		_spec.ClearField(sslscan.FieldCertSubject, field.TypeString)
	}
	if value, ok := _u.mutation.CertExpiry(); ok {
		_spec.SetField(sslscan.FieldCertExpiry, field.TypeTime, value)
	}
	if _u.mutation.CertExpiryCleared() {
		_spec.ClearField(sslscan.FieldCertExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Protocols(); ok {
		_spec.SetField(sslscan.FieldProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sslscan.FieldProtocols, value)
		})
	}
	if _u.mutation.ProtocolsCleared() {
		_spec.ClearField(sslscan.FieldProtocols, field.TypeJSON)
	}
	if value, ok := _u.mutation.Vulnerabilities(); ok {
		_spec.SetField(sslscan.FieldVulnerabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVulnerabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sslscan.FieldVulnerabilities, value)
		})
	}
	if _u.mutation.VulnerabilitiesCleared() {
		_spec.ClearField(sslscan.FieldVulnerabilities, field.TypeJSON)
	}
	if _u.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sslscan.TargetTable,
			Columns: []string{sslscan.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sslscan.TargetTable,
			Columns: []string{sslscan.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SSLScan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sslscan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
