// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"perimeter/ent/sslscan"
	"perimeter/ent/target"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SSLScan is the model entity for the SSLScan schema.
type SSLScan struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ScannedAt holds the value of the "scanned_at" field.
	ScannedAt time.Time `json:"scanned_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CheckCount holds the value of the "check_count" field.
	CheckCount int `json:"check_count,omitempty"`
	// Grade holds the value of the "grade" field.
	Grade string `json:"grade,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CertIssuer holds the value of the "cert_issuer" field.
	CertIssuer string `json:"cert_issuer,omitempty"`
	// CertSubject holds the value of the "cert_subject" field.
	CertSubject string `json:"cert_subject,omitempty"`
	// CertExpiry holds the value of the "cert_expiry" field.
	CertExpiry time.Time `json:"cert_expiry,omitempty"`
	// Protocols holds the value of the "protocols" field.
	Protocols []string `json:"protocols,omitempty"`
	// Vulnerabilities holds the value of the "vulnerabilities" field.
	Vulnerabilities []string `json:"vulnerabilities,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SSLScanQuery when eager-loading is set.
	Edges            SSLScanEdges `json:"edges"`
	target_ssl_scans *int
	selectValues     sql.SelectValues
}

// SSLScanEdges holds the relations/edges for other nodes in the graph.
type SSLScanEdges struct {
	// Target holds the value of the target edge.
	Target *Target `json:"target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SSLScanEdges) TargetOrErr() (*Target, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: target.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SSLScan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sslscan.FieldProtocols, sslscan.FieldVulnerabilities:
			values[i] = new([]byte)
		case sslscan.FieldID, sslscan.FieldCheckCount:
			values[i] = new(sql.NullInt64)
		case sslscan.FieldGrade, sslscan.FieldStatus, sslscan.FieldCertIssuer, sslscan.FieldCertSubject:
			values[i] = new(sql.NullString)
		case sslscan.FieldScannedAt, sslscan.FieldLastSeenAt, sslscan.FieldCertExpiry:
			values[i] = new(sql.NullTime)
		case sslscan.ForeignKeys[0]: // target_ssl_scans
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SSLScan fields.
func (_m *SSLScan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sslscan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sslscan.FieldScannedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scanned_at", values[i])
			} else if value.Valid {
				_m.ScannedAt = value.Time
			}
		case sslscan.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case sslscan.FieldCheckCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field check_count", values[i])
			} else if value.Valid {
				_m.CheckCount = int(value.Int64)
			}
		case sslscan.FieldGrade:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grade", values[i])
			} else if value.Valid {
				_m.Grade = value.String
			}
		case sslscan.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sslscan.FieldCertIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cert_issuer", values[i])
			} else if value.Valid {
				_m.CertIssuer = value.String
			}
		case sslscan.FieldCertSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cert_subject", values[i])
			} else if value.Valid {
				_m.CertSubject = value.String
			}
		case sslscan.FieldCertExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cert_expiry", values[i])
			} else if value.Valid {
				_m.CertExpiry = value.Time
			}
		case sslscan.FieldProtocols:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field protocols", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Protocols); err != nil {
					return fmt.Errorf("unmarshal field protocols: %w", err)
				}
			}
		case sslscan.FieldVulnerabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field vulnerabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Vulnerabilities); err != nil {
					return fmt.Errorf("unmarshal field vulnerabilities: %w", err)
				}
			}
		case sslscan.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field target_ssl_scans", value)
			} else if value.Valid {
				_m.target_ssl_scans = new(int)
				*_m.target_ssl_scans = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SSLScan.
// This includes values selected through modifiers, order, etc.
func (_m *SSLScan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTarget queries the "target" edge of the SSLScan entity.
func (_m *SSLScan) QueryTarget() *TargetQuery {
	return NewSSLScanClient(_m.config).QueryTarget(_m)
}

// Update returns a builder for updating this SSLScan.
// Note that you need to call SSLScan.Unwrap() before calling this method if this SSLScan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SSLScan) Update() *SSLScanUpdateOne {
	return NewSSLScanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SSLScan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SSLScan) Unwrap() *SSLScan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SSLScan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SSLScan) String() string {
	var builder strings.Builder
	builder.WriteString("SSLScan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scanned_at=")
	builder.WriteString(_m.ScannedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("check_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CheckCount))
	builder.WriteString(", ")
	builder.WriteString("grade=")
	builder.WriteString(_m.Grade)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("cert_issuer=")
	builder.WriteString(_m.CertIssuer)
	builder.WriteString(", ")
	builder.WriteString("cert_subject=")
	builder.WriteString(_m.CertSubject)
	builder.WriteString(", ")
	builder.WriteString("cert_expiry=")
	builder.WriteString(_m.CertExpiry.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("protocols=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocols))
	builder.WriteString(", ")
	builder.WriteString("vulnerabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Vulnerabilities))
	builder.WriteByte(')')
	return builder.String()
}

// SSLScans is a parsable slice of SSLScan.
type SSLScans []*SSLScan
