// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"perimeter/ent/target"
	"perimeter/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Target is the model entity for the Target schema.
type Target struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Input holds the value of the "input" field.
	Input string `json:"input,omitempty"`
	// IsIP holds the value of the "is_ip" field.
	IsIP bool `json:"is_ip,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TargetQuery when eager-loading is set.
	Edges        TargetEdges `json:"edges"`
	user_targets *int
	selectValues sql.SelectValues
}

// TargetEdges holds the relations/edges for other nodes in the graph.
type TargetEdges struct {
	// Ips holds the value of the ips edge.
	Ips []*IP `json:"ips,omitempty"`
	// SslScans holds the value of the ssl_scans edge.
	SslScans []*SSLScan `json:"ssl_scans,omitempty"`
	// CspScans holds the value of the csp_scans edge.
	CspScans []*CSPScan `json:"csp_scans,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// IpsOrErr returns the Ips value or an error if the edge
// was not loaded in eager-loading.
func (e TargetEdges) IpsOrErr() ([]*IP, error) {
	if e.loadedTypes[0] {
		return e.Ips, nil
	}
	return nil, &NotLoadedError{edge: "ips"}
}

// SslScansOrErr returns the SslScans value or an error if the edge
// was not loaded in eager-loading.
func (e TargetEdges) SslScansOrErr() ([]*SSLScan, error) {
	if e.loadedTypes[1] {
		return e.SslScans, nil
	}
	return nil, &NotLoadedError{edge: "ssl_scans"}
}

// CspScansOrErr returns the CspScans value or an error if the edge
// was not loaded in eager-loading.
func (e TargetEdges) CspScansOrErr() ([]*CSPScan, error) {
	if e.loadedTypes[2] {
		return e.CspScans, nil
	}
	return nil, &NotLoadedError{edge: "csp_scans"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TargetEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Target) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case target.FieldIsIP:
			values[i] = new(sql.NullBool)
		case target.FieldID:
			values[i] = new(sql.NullInt64)
		case target.FieldInput:
			values[i] = new(sql.NullString)
		case target.FieldCreateTime, target.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case target.ForeignKeys[0]: // user_targets
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Target fields.
func (_m *Target) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case target.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case target.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case target.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case target.FieldInput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input", values[i])
			} else if value.Valid {
				_m.Input = value.String
			}
		case target.FieldIsIP:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_ip", values[i])
			} else if value.Valid {
				_m.IsIP = value.Bool
			}
		case target.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_targets", value)
			} else if value.Valid {
				_m.user_targets = new(int)
				*_m.user_targets = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Target.
// This includes values selected through modifiers, order, etc.
func (_m *Target) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIps queries the "ips" edge of the Target entity.
func (_m *Target) QueryIps() *IPQuery {
	return NewTargetClient(_m.config).QueryIps(_m)
}

// QuerySslScans queries the "ssl_scans" edge of the Target entity.
func (_m *Target) QuerySslScans() *SSLScanQuery {
	return NewTargetClient(_m.config).QuerySslScans(_m)
}

// QueryCspScans queries the "csp_scans" edge of the Target entity.
func (_m *Target) QueryCspScans() *CSPScanQuery {
	return NewTargetClient(_m.config).QueryCspScans(_m)
}

// QueryOwner queries the "owner" edge of the Target entity.
func (_m *Target) QueryOwner() *UserQuery {
	return NewTargetClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this Target.
// Note that you need to call Target.Unwrap() before calling this method if this Target
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Target) Update() *TargetUpdateOne {
	return NewTargetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Target entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Target) Unwrap() *Target {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Target is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Target) String() string {
	var builder strings.Builder
	builder.WriteString("Target(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("input=")
	builder.WriteString(_m.Input)
	builder.WriteString(", ")
	builder.WriteString("is_ip=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsIP))
	builder.WriteByte(')')
	return builder.String()
}

// Targets is a parsable slice of Target.
type Targets []*Target
