// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/portscan"
	"perimeter/ent/predicate"
	"perimeter/ent/target"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TargetUpdate is the builder for updating Target entities.
type TargetUpdate struct {
	config
	hooks    []Hook
	mutation *TargetMutation
}

// Where appends a list predicates to the TargetUpdate builder.
func (_u *TargetUpdate) Where(ps ...predicate.Target) *TargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TargetUpdate) SetUpdateTime(v time.Time) *TargetUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetInput sets the "input" field.
func (_u *TargetUpdate) SetInput(v string) *TargetUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *TargetUpdate) SetNillableInput(v *string) *TargetUpdate {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// AddScanIDs adds the "scans" edge to the PortScan entity by IDs.
func (_u *TargetUpdate) AddScanIDs(ids ...int) *TargetUpdate {
	_u.mutation.AddScanIDs(ids...)
	return _u
}

// AddScans adds the "scans" edges to the PortScan entity.
func (_u *TargetUpdate) AddScans(v ...*PortScan) *TargetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScanIDs(ids...)
}

// Mutation returns the TargetMutation object of the builder.
func (_u *TargetUpdate) Mutation() *TargetMutation {
	return _u.mutation
}

// ClearScans clears all "scans" edges to the PortScan entity.
func (_u *TargetUpdate) ClearScans() *TargetUpdate {
	_u.mutation.ClearScans()
	return _u
}

// RemoveScanIDs removes the "scans" edge to PortScan entities by IDs.
func (_u *TargetUpdate) RemoveScanIDs(ids ...int) *TargetUpdate {
	_u.mutation.RemoveScanIDs(ids...)
	return _u
}

// RemoveScans removes "scans" edges to PortScan entities.
func (_u *TargetUpdate) RemoveScans(v ...*PortScan) *TargetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TargetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TargetUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := target.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TargetUpdate) check() error {
	if v, ok := _u.mutation.Input(); ok {
		if err := target.InputValidator(v); err != nil {
			return &ValidationError{Name: "input", err: fmt.Errorf(`ent: validator failed for field "Target.input": %w`, err)}
		}
	}
	return nil
}

func (_u *TargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(target.Table, target.Columns, sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(target.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(target.FieldInput, field.TypeString, value)
	}
	if _u.mutation.ScansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScansIDs(); len(nodes) > 0 && !_u.mutation.ScansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{target.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TargetUpdateOne is the builder for updating a single Target entity.
type TargetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TargetMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *TargetUpdateOne) SetUpdateTime(v time.Time) *TargetUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetInput sets the "input" field.
func (_u *TargetUpdateOne) SetInput(v string) *TargetUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *TargetUpdateOne) SetNillableInput(v *string) *TargetUpdateOne {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// AddScanIDs adds the "scans" edge to the PortScan entity by IDs.
func (_u *TargetUpdateOne) AddScanIDs(ids ...int) *TargetUpdateOne {
	_u.mutation.AddScanIDs(ids...)
	return _u
}

// AddScans adds the "scans" edges to the PortScan entity.
func (_u *TargetUpdateOne) AddScans(v ...*PortScan) *TargetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScanIDs(ids...)
}

// Mutation returns the TargetMutation object of the builder.
func (_u *TargetUpdateOne) Mutation() *TargetMutation {
	return _u.mutation
}

// ClearScans clears all "scans" edges to the PortScan entity.
func (_u *TargetUpdateOne) ClearScans() *TargetUpdateOne {
	_u.mutation.ClearScans()
	return _u
}

// RemoveScanIDs removes the "scans" edge to PortScan entities by IDs.
func (_u *TargetUpdateOne) RemoveScanIDs(ids ...int) *TargetUpdateOne {
	_u.mutation.RemoveScanIDs(ids...)
	return _u
}

// RemoveScans removes "scans" edges to PortScan entities.
func (_u *TargetUpdateOne) RemoveScans(v ...*PortScan) *TargetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScanIDs(ids...)
}

// Where appends a list predicates to the TargetUpdate builder.
func (_u *TargetUpdateOne) Where(ps ...predicate.Target) *TargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TargetUpdateOne) Select(field string, fields ...string) *TargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Target entity.
func (_u *TargetUpdateOne) Save(ctx context.Context) (*Target, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TargetUpdateOne) SaveX(ctx context.Context) *Target {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TargetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := target.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TargetUpdateOne) check() error {
	if v, ok := _u.mutation.Input(); ok {
		if err := target.InputValidator(v); err != nil {
			return &ValidationError{Name: "input", err: fmt.Errorf(`ent: validator failed for field "Target.input": %w`, err)}
		}
	}
	return nil
}

func (_u *TargetUpdateOne) sqlSave(ctx context.Context) (_node *Target, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(target.Table, target.Columns, sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Target.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, target.FieldID)
		for _, f := range fields {
			if !target.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != target.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(target.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(target.FieldInput, field.TypeString, value)
	}
	if _u.mutation.ScansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScansIDs(); len(nodes) > 0 && !_u.mutation.ScansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.ScansTable,
			Columns: []string{target.ScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Target{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{target.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
