// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"perimeter/ent/cspscan"
	"perimeter/ent/ip"
	"perimeter/ent/sslscan"
	"perimeter/ent/target"
	"perimeter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TargetCreate is the builder for creating a Target entity.
type TargetCreate struct {
	config
	mutation *TargetMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *TargetCreate) SetCreateTime(v time.Time) *TargetCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TargetCreate) SetNillableCreateTime(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TargetCreate) SetUpdateTime(v time.Time) *TargetCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TargetCreate) SetNillableUpdateTime(v *time.Time) *TargetCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetInput sets the "input" field.
func (_c *TargetCreate) SetInput(v string) *TargetCreate {
	_c.mutation.SetInput(v)
	return _c
}

// SetIsIP sets the "is_ip" field.
func (_c *TargetCreate) SetIsIP(v bool) *TargetCreate {
	_c.mutation.SetIsIP(v)
	return _c
}

// SetNillableIsIP sets the "is_ip" field if the given value is not nil.
func (_c *TargetCreate) SetNillableIsIP(v *bool) *TargetCreate {
	if v != nil {
		_c.SetIsIP(*v)
	}
	return _c
}

// AddIPIDs adds the "ips" edge to the IP entity by IDs.
func (_c *TargetCreate) AddIPIDs(ids ...int) *TargetCreate {
	_c.mutation.AddIPIDs(ids...)
	return _c
}

// AddIps adds the "ips" edges to the IP entity.
func (_c *TargetCreate) AddIps(v ...*IP) *TargetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIPIDs(ids...)
}

// AddSslScanIDs adds the "ssl_scans" edge to the SSLScan entity by IDs.
func (_c *TargetCreate) AddSslScanIDs(ids ...int) *TargetCreate {
	_c.mutation.AddSslScanIDs(ids...)
	return _c
}

// AddSslScans adds the "ssl_scans" edges to the SSLScan entity.
func (_c *TargetCreate) AddSslScans(v ...*SSLScan) *TargetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSslScanIDs(ids...)
}

// AddCspScanIDs adds the "csp_scans" edge to the CSPScan entity by IDs.
func (_c *TargetCreate) AddCspScanIDs(ids ...int) *TargetCreate {
	_c.mutation.AddCspScanIDs(ids...)
	return _c
}

// AddCspScans adds the "csp_scans" edges to the CSPScan entity.
func (_c *TargetCreate) AddCspScans(v ...*CSPScan) *TargetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCspScanIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *TargetCreate) SetOwnerID(id int) *TargetCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *TargetCreate) SetNillableOwnerID(id *int) *TargetCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *TargetCreate) SetOwner(v *User) *TargetCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the TargetMutation object of the builder.
func (_c *TargetCreate) Mutation() *TargetMutation {
	return _c.mutation
}

// Save creates the Target in the database.
func (_c *TargetCreate) Save(ctx context.Context) (*Target, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TargetCreate) SaveX(ctx context.Context) *Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TargetCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := target.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := target.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsIP(); !ok {
		v := target.DefaultIsIP
		_c.mutation.SetIsIP(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TargetCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Target.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Target.update_time"`)}
	}
	if _, ok := _c.mutation.Input(); !ok {
		return &ValidationError{Name: "input", err: errors.New(`ent: missing required field "Target.input"`)}
	}
	if v, ok := _c.mutation.Input(); ok {
		if err := target.InputValidator(v); err != nil {
			return &ValidationError{Name: "input", err: fmt.Errorf(`ent: validator failed for field "Target.input": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsIP(); !ok {
		return &ValidationError{Name: "is_ip", err: errors.New(`ent: missing required field "Target.is_ip"`)}
	}
	return nil
}

func (_c *TargetCreate) sqlSave(ctx context.Context) (*Target, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TargetCreate) createSpec() (*Target, *sqlgraph.CreateSpec) {
	var (
		_node = &Target{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(target.Table, sqlgraph.NewFieldSpec(target.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(target.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(target.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(target.FieldInput, field.TypeString, value)
		_node.Input = value
	}
	if value, ok := _c.mutation.IsIP(); ok {
		_spec.SetField(target.FieldIsIP, field.TypeBool, value)
		_node.IsIP = value
	}
	if nodes := _c.mutation.IpsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   target.IpsTable,
			Columns: target.IpsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SslScansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.SslScansTable,
			Columns: []string{target.SslScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sslscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CspScansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   target.CspScansTable,
			Columns: []string{target.CspScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cspscan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   target.OwnerTable,
			Columns: []string{target.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_targets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TargetCreateBulk is the builder for creating many Target entities in bulk.
type TargetCreateBulk struct {
	config
	err      error
	builders []*TargetCreate
}

// Save creates the Target entities in the database.
func (_c *TargetCreateBulk) Save(ctx context.Context) ([]*Target, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Target, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TargetCreateBulk) SaveX(ctx context.Context) []*Target {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
