// Code generated by ent, DO NOT EDIT.

package portscan

import (
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldID, id))
}

// ScannedAt applies equality check predicate on the "scanned_at" field. It's identical to ScannedAtEQ.
func ScannedAt(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldScannedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// CheckCount applies equality check predicate on the "check_count" field. It's identical to CheckCountEQ.
func CheckCount(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldCheckCount, v))
}

// ScannedAtEQ applies the EQ predicate on the "scanned_at" field.
func ScannedAtEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldScannedAt, v))
}

// ScannedAtNEQ applies the NEQ predicate on the "scanned_at" field.
func ScannedAtNEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldScannedAt, v))
}

// ScannedAtIn applies the In predicate on the "scanned_at" field.
func ScannedAtIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldScannedAt, vs...))
}

// ScannedAtNotIn applies the NotIn predicate on the "scanned_at" field.
func ScannedAtNotIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldScannedAt, vs...))
}

// ScannedAtGT applies the GT predicate on the "scanned_at" field.
func ScannedAtGT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldScannedAt, v))
}

// ScannedAtGTE applies the GTE predicate on the "scanned_at" field.
func ScannedAtGTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldScannedAt, v))
}

// ScannedAtLT applies the LT predicate on the "scanned_at" field.
func ScannedAtLT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldScannedAt, v))
}

// ScannedAtLTE applies the LTE predicate on the "scanned_at" field.
func ScannedAtLTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldScannedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.PortScan {
	return predicate.PortScan(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.PortScan {
	return predicate.PortScan(sql.FieldNotNull(FieldLastSeenAt))
}

// CheckCountEQ applies the EQ predicate on the "check_count" field.
func CheckCountEQ(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldCheckCount, v))
}

// CheckCountNEQ applies the NEQ predicate on the "check_count" field.
func CheckCountNEQ(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldCheckCount, v))
}

// CheckCountIn applies the In predicate on the "check_count" field.
func CheckCountIn(vs ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldCheckCount, vs...))
}

// CheckCountNotIn applies the NotIn predicate on the "check_count" field.
func CheckCountNotIn(vs ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldCheckCount, vs...))
}

// CheckCountGT applies the GT predicate on the "check_count" field.
func CheckCountGT(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldCheckCount, v))
}

// CheckCountGTE applies the GTE predicate on the "check_count" field.
func CheckCountGTE(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldCheckCount, v))
}

// CheckCountLT applies the LT predicate on the "check_count" field.
func CheckCountLT(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldCheckCount, v))
}

// CheckCountLTE applies the LTE predicate on the "check_count" field.
func CheckCountLTE(v int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldCheckCount, v))
}

// HasIP applies the HasEdge predicate on the "ip" edge.
func HasIP() predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IPTable, IPColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIPWith applies the HasEdge predicate on the "ip" edge with a given conditions (other predicates).
func HasIPWith(preds ...predicate.IP) predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := newIPStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPorts applies the HasEdge predicate on the "ports" edge.
func HasPorts() predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PortsTable, PortsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPortsWith applies the HasEdge predicate on the "ports" edge with a given conditions (other predicates).
func HasPortsWith(preds ...predicate.Port) predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := newPortsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.NotPredicates(p))
}
