// Code generated by ent, DO NOT EDIT.

package portscan

import (
	"perimeter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldID, id))
}

// ScannedAt applies equality check predicate on the "scanned_at" field. It's identical to ScannedAtEQ.
func ScannedAt(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldScannedAt, v))
}

// ScannedAtEQ applies the EQ predicate on the "scanned_at" field.
func ScannedAtEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldEQ(FieldScannedAt, v))
}

// ScannedAtNEQ applies the NEQ predicate on the "scanned_at" field.
func ScannedAtNEQ(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNEQ(FieldScannedAt, v))
}

// ScannedAtIn applies the In predicate on the "scanned_at" field.
func ScannedAtIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldIn(FieldScannedAt, vs...))
}

// ScannedAtNotIn applies the NotIn predicate on the "scanned_at" field.
func ScannedAtNotIn(vs ...time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldNotIn(FieldScannedAt, vs...))
}

// ScannedAtGT applies the GT predicate on the "scanned_at" field.
func ScannedAtGT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGT(FieldScannedAt, v))
}

// ScannedAtGTE applies the GTE predicate on the "scanned_at" field.
func ScannedAtGTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldGTE(FieldScannedAt, v))
}

// ScannedAtLT applies the LT predicate on the "scanned_at" field.
func ScannedAtLT(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLT(FieldScannedAt, v))
}

// ScannedAtLTE applies the LTE predicate on the "scanned_at" field.
func ScannedAtLTE(v time.Time) predicate.PortScan {
	return predicate.PortScan(sql.FieldLTE(FieldScannedAt, v))
}

// HasTargets applies the HasEdge predicate on the "targets" edge.
func HasTargets() predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TargetsTable, TargetsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetsWith applies the HasEdge predicate on the "targets" edge with a given conditions (other predicates).
func HasTargetsWith(preds ...predicate.Target) predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := newTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPorts applies the HasEdge predicate on the "ports" edge.
func HasPorts() predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PortsTable, PortsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPortsWith applies the HasEdge predicate on the "ports" edge with a given conditions (other predicates).
func HasPortsWith(preds ...predicate.Port) predicate.PortScan {
	return predicate.PortScan(func(s *sql.Selector) {
		step := newPortsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PortScan) predicate.PortScan {
	return predicate.PortScan(sql.NotPredicates(p))
}
