// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CSPScan is the predicate function for cspscan builders.
type CSPScan func(*sql.Selector)

// IP is the predicate function for ip builders.
type IP func(*sql.Selector)

// Port is the predicate function for port builders.
type Port func(*sql.Selector)

// PortScan is the predicate function for portscan builders.
type PortScan func(*sql.Selector)

// SSLScan is the predicate function for sslscan builders.
type SSLScan func(*sql.Selector)

// Target is the predicate function for target builders.
type Target func(*sql.Selector)
